"""The DSM indicators are DERIVED from the vendored FAIRplus assessment workbook
(``fair/fairplus_dsm_v1.2.xlsx``), not hand-authored.

``fair/dsm_indicators.yaml`` is generated by ``scripts/gen_dsm_indicators.py`` from the
workbook's "MASTER (Levels View)" sheet (definitions: level / category / verbatim text /
granularity / the model's own RDA + FAIRsFAIR cross-references) plus a local scope/check
map. These tests pin that contract so the published model can never silently drift into a
paraphrase, and so the paper's claim to be scoring *the FAIRplus DSM* stays true.

The prior hand-curated file carried 28 entries — 25 of the 83 published indicators, one
invented id (``DSM-5``), paraphrased text, and level names found nowhere in the model.
"""

from __future__ import annotations

import html
import importlib.util
import re
import pathlib

import openpyxl
import yaml

REPO = pathlib.Path(__file__).resolve().parents[1]
DSM_YAML = REPO / "fair" / "dsm_indicators.yaml"
DSM_XLSX = REPO / "fair" / "fairplus_dsm_v1.2.xlsx"
GEN = REPO / "scripts" / "gen_dsm_indicators.py"

# The published model, as distributed in v1.2 of the assessment sheet.
PUBLISHED_TOTAL = 83
PUBLISHED_PER_LEVEL = {0: 11, 1: 14, 2: 15, 3: 16, 4: 14, 5: 13}
PUBLISHED_PER_CATEGORY = {"C": 31, "R": 32, "H": 20}

# The assessment sheet's own "% Complete" cells. Larger than the level's indicator
# count wherever the sheet carries lower levels forward, and smaller at Level 5, whose
# enterprise-governance rows mostly appear on no assessment row at all.
SHEET_CELL_TOTALS = {0: 11, 1: 14, 2: 21, 3: 22, 4: 15, 5: 5}


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_dsm_indicators", GEN)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _yaml() -> dict:
    return yaml.safe_load(DSM_YAML.read_text())


def _workbook_rows() -> dict[str, dict]:
    """Indicator id -> row, read straight from the vendored workbook."""
    wb = openpyxl.load_workbook(DSM_XLSX, read_only=True, data_only=True)
    ws = wb["MASTER (Levels View)"]
    out: dict[str, dict] = {}
    level = None
    for row in list(ws.iter_rows(values_only=True))[1:]:
        if row[0] not in (None, ""):
            try:
                level = int(float(row[0]))
            except (TypeError, ValueError):
                pass
        ident = str(row[2]).strip() if row[2] else ""
        if not ident.startswith("DSM-"):
            continue
        out[ident] = {
            "level": level,
            "text": str(row[4]).strip() if row[4] else "",
            "granularity": str(row[7]).strip() if row[7] else "",
        }
    return out


class TestGeneratedFromTheWorkbook:
    """The committed YAML is exactly what the generator produces from the workbook."""

    def test_committed_yaml_equals_generator_output(self):
        mod = _load_generator()
        assert _yaml() == mod.build_data(), (
            "fair/dsm_indicators.yaml is stale or hand-edited — "
            "regenerate with `uv run python scripts/gen_dsm_indicators.py`"
        )

    def test_the_vendored_workbook_is_present(self):
        assert DSM_XLSX.is_file() and DSM_XLSX.stat().st_size > 100_000


class TestTheWholePublishedModelIsCarried:
    """All 83 indicators, not the subset we happen to assess."""

    def test_every_published_indicator_is_present(self):
        ids = {i["id"] for i in _yaml()["indicators"]}
        assert ids == set(_workbook_rows())
        assert len(ids) == PUBLISHED_TOTAL

    def test_counts_per_level_and_category(self):
        inds = _yaml()["indicators"]
        per_level: dict[int, int] = {}
        per_cat: dict[str, int] = {}
        for i in inds:
            per_level[i["level"]] = per_level.get(i["level"], 0) + 1
            per_cat[i["category"]] = per_cat.get(i["category"], 0) + 1
        assert per_level == PUBLISHED_PER_LEVEL
        assert per_cat == PUBLISHED_PER_CATEGORY

    def test_indicator_text_is_verbatim_never_paraphrased(self):
        rows = _workbook_rows()
        for ind in _yaml()["indicators"]:
            src = rows[ind["id"]]
            assert ind["text"] == src["text"], f"{ind['id']} text drifted from the model"
            assert ind["level"] == src["level"], f"{ind['id']} level drifted"
            assert ind["granularity"] == src["granularity"], f"{ind['id']} granularity drifted"

    def test_no_invented_identifiers_survive(self):
        """The old file carried a bare ``DSM-5`` placeholder that the model never defined."""
        ids = {i["id"] for i in _yaml()["indicators"]}
        assert "DSM-5" not in ids
        # Every id is <model>-<level>-<category><n>, so a bare level id cannot recur.
        for iid in ids:
            assert iid.count("-") >= 2, f"{iid} is not a published DSM identifier"


class TestLevelNamesComeFromTheModel:
    """The old file named the levels after organisational tiers the model never uses."""

    def test_level_names_are_the_models_state_of_data(self):
        assert _yaml()["levels"] == {
            0: "Single-use data",
            1: "Identifiable Data",
            2: "Described Data",
            3: "Standardised Data",
            4: "Semantically Typed Data",
            5: "Managed Data Assets",
        }

    def test_the_invented_organisational_names_are_gone(self):
        text = DSM_YAML.read_text()
        for invented in ("Individual researcher", "Consortium", "Institutional data commons"):
            assert invented not in text, f"stale level name {invented!r} survives"


class TestLocalScopeIsHonest:
    """What we assess is declared per indicator, and never inflated."""

    def test_every_scoped_indicator_names_a_registered_check(self):
        from builder.tools.fair_assessment import DSM_CHECKS

        for ind in _yaml()["indicators"]:
            if ind["scope"] == "na":
                assert "check" not in ind, f"{ind['id']} is na but names a check"
                continue
            assert ind.get("check") in DSM_CHECKS, (
                f"{ind['id']} is scoped {ind['scope']!r} but its check "
                f"{ind.get('check')!r} is not registered in DSM_CHECKS"
            )

    def test_hosting_indicators_are_never_claimed_as_assessable(self):
        """A crate on disk cannot evidence its hosting environment's capabilities."""
        for ind in _yaml()["indicators"]:
            if ind["category"] == "H":
                assert ind["scope"] == "na", f"{ind['id']} is a hosting indicator"

    def test_level_zero_is_never_scored(self):
        """Level 0 states the pre-FAIR condition in the negative; passing it is bad."""
        for ind in _yaml()["indicators"]:
            if ind["level"] == 0:
                assert ind["scope"] == "na", f"{ind['id']} is a Level-0 negative state"

    def test_the_model_s_own_rda_cross_references_are_carried(self):
        """27 indicators cite an RDA indicator — the published bridge between the axes."""
        linked = [i for i in _yaml()["indicators"] if i.get("rda_ref")]
        assert len(linked) == 27
        assert all(i["rda_ref"].startswith(("RDA-", "[")) for i in linked)


class TestProvenanceIsRecorded:
    """The paper cites this file; it must say where it came from."""

    def test_source_block_names_the_distribution_and_licence(self):
        src = _yaml()["source"]
        assert src["version"] == "1.2"
        # The MODEL is CC BY 4.0. The repo's MIT LICENSE.txt covers only its Jekyll
        # theme; recording MIT here would under-attribute a work the paper cites.
        assert src["license"] == "CC-BY-4.0"
        assert src["specification"]["doi"] == "10.5281/zenodo.7464523"
        assert src["peer_reviewed"]["doi"] == "10.1038/s41597-023-02167-2"
        assert "FAIRplus" in src["name"] and "Dataset Maturity" in src["name"]
        assert "fairplus_dsm_v1.2.xlsx" in src["distribution"]
        assert src["repository"] == "https://github.com/FAIRplus/Data-Maturity"

    def test_it_records_that_the_model_assesses_a_dataset(self):
        """Guards the misreading that DSM scores an organisation's capability."""
        assert "DATASET, not an organisation" in _yaml()["source"]["note"]


class TestTheGeneratorRefusesToLie:
    """The generator fails loudly rather than scoring something that is not there."""

    def test_unknown_indicator_in_local_scope_raises(self):
        mod = _load_generator()
        original = dict(mod.LOCAL_SCOPE)
        mod.LOCAL_SCOPE["DSM-9-C9"] = ("full", "unique_id")
        try:
            with __import__("pytest").raises(KeyError, match="absent from the workbook"):
                mod.build_data()
        finally:
            mod.LOCAL_SCOPE.clear()
            mod.LOCAL_SCOPE.update(original)


class TestTheReport:
    """`gen_dsm_indicators.py` prints a per-level coverage summary (user request)."""

    def test_report_states_coverage_per_level(self):
        mod = _load_generator()
        report = mod.format_report(mod.build_data())
        assert "FAIRplus Dataset Maturity Model (DSM) v1.2" in report
        for name in ("Single-use data", "Identifiable Data", "Managed Data Assets"):
            assert name in report
        assert "hosting-environment" in report
        assert "83" in report


class TestTheModelsOwnPercentCompleteGrid:
    """`dsm_grid` reproduces the assessment sheet's 6x3 "% Complete" scoring.

    The sheet's formula, verbatim from cell P10 (Level 1, Content and context)::

        =(((COUNTIFS(J32,1))+(COUNTIFS(J45,1))+(COUNTIFS(J50,1))+(COUNTIFS(J51,1)))
          /(COUNT(J32,J45,J50,J51))*100)

    and P6 (Level 0), which counts ZEROS rather than ones::

        =(((COUNTIFS(J31,0))+(COUNTIFS(J44,0))+(COUNTIFS(J49,0)))/(COUNT(J31,J44,J49))*100)
    """

    def _grid(self):
        from builder.tools.fair_assessment import dsm_grid
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        return dsm_grid(vhps_fixture_state("S-VHPS21"))

    def test_the_grid_covers_every_published_cell(self):
        """Cell membership is the sheet's, not "the indicators at this level".

        A level's cell carries lower levels forward, so its size is not the MASTER
        census (``PUBLISHED_PER_LEVEL``) — the Level-2 cells hold 21 slots, six more
        than Level 2 has indicators.
        """
        grid = self._grid()
        assert set(grid) == set(PUBLISHED_PER_LEVEL)
        for level, by_cat in grid.items():
            assert set(by_cat) == {"C", "R", "H", "TOTAL"}, level
            assert by_cat["TOTAL"]["total"] == SHEET_CELL_TOTALS[level]

    def test_every_cell_states_both_numbers(self):
        """``published_pct`` is the sheet's arithmetic; ``pct`` is over what we assessed.

        The sheet cannot say "not assessed" — its validation column is all formulas, so
        a blank scores 0 — but this tool can, and publishing only the sheet's number
        would report a Level-0 row of 100% on the strength of never having looked.
        Both are carried so the coverage behind each percentage is visible.
        """
        for by_cat in self._grid().values():
            for cell in by_cat.values():
                assert cell["assessed"] <= cell["total"]
                assert isinstance(cell["published_pct"], float), cell["cell"]
                if cell["assessed"]:
                    assert cell["pct"] == round(cell["passed"] / cell["assessed"] * 100, 1)
                    assert cell["passed"] <= cell["assessed"]
                else:
                    assert cell["pct"] is None, cell["cell"]

    def test_an_unassessable_cell_is_none_never_zero(self):
        """"Not assessed" is not the same claim as 0%, so ``pct`` says so."""
        grid = self._grid()
        for level in (0, 5):
            for cell in grid[level].values():
                assert cell["assessed"] == 0
                assert cell["pct"] is None
        for by_cat in grid.values():
            hosting = by_cat.get("H")
            if hosting:
                assert hosting["pct"] is None, "no crate can evidence its hosting environment"

    def test_level_zero_is_scored_inverted(self):
        """Level 0 counts ZEROS (P6). Satisfying "data is NOT identifiable" is bad.

        Driven through the real scorer rather than asserted structurally: a
        level-0 indicator wired to a check that PASSES must score 0 there, which
        is the opposite of every other level.

        The driving check was ``unique_id`` until #670 moved it onto the assembled
        crate, where it answers "not assessed" without a graph — an unanswered cell
        leaves the denominator, so neither rung would score and the inversion would
        go untested. ``has_descriptor`` is one of the checks that still answers from
        ``CrateState``, so it drives the same test with a graph-free fixture.
        """
        from builder.tools import fair_assessment as fa
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        data = {
            "indicators": [
                {"id": "DSM-0-C0", "level": 0, "category": "C",
                 "scope": "full", "check": "has_descriptor"},
                {"id": "DSM-1-C0", "level": 1, "category": "C",
                 "scope": "full", "check": "has_descriptor"},
            ],
            "scoring": {
                "grid": [
                    {"cell": "P6", "level": 0, "category": "C", "counts": 0,
                     "members": ["DSM-0-C0"], "denominator": {"kind": "count", "n": 1}},
                    {"cell": "P10", "level": 1, "category": "C", "counts": 1,
                     "members": ["DSM-1-C0"], "denominator": {"kind": "count", "n": 1}},
                ]
            },
        }
        state = vhps_fixture_state("S-VHPS21")
        assert fa.DSM_CHECKS["has_descriptor"](state, None) is True
        grid = fa.dsm_grid(state, data)
        assert grid[0]["C"]["passed"] == 0, "a satisfied Level-0 negative must not score"
        assert grid[1]["C"]["passed"] == 1, "the same check at Level 1 must score"

    def test_the_report_renders_the_grid_faithfully(self):
        from builder.writers.maturity_report import build_maturity_html
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        page = build_maturity_html(vhps_fixture_state("S-VHPS21"))
        assert "FAIRplus Dataset Maturity Model</h2>" in page
        # Every level the tool reports is a row label. Level 0 is not one of them.
        for level, name in _yaml()["levels"].items():
            assert (name in page) is (level >= 1), name
        # The tool's own column headings, in its own order.
        assert page.index("Representation &amp; Format") < page.index("Content &amp; Context")
        assert "Overall Level % Completion" in page
        # The sheet's own number in every cell — an unanswered indicator validates to 0
        # there, so it lowers the percentage rather than leaving it — with the coverage
        # beside it, so a low number is not mistaken for a measured failure.
        assert "0 of 4 assessed" in page
        assert "not assessed" not in page.split('class="dsm-grid"', 1)[-1].split("</table>", 1)[0]
        # The two properties a reader needs to interpret the numbers are stated.
        # The two properties a reader needs to interpret the numbers.
        assert "a blank scores 0" in page
        assert "higher levels carry lower ones forward" in page


class TestNoGraphMeansUnanswered:
    """A graph-aware check with no graph answers ``None``, never ``False``.

    The DSM's Level 2-4 field/value indicators live in the assembled ``@graph``.
    Answering ``False`` when no graph was supplied would read as "the crate fails
    this indicator" when the truth is "nothing was assessed" — and it would drag the
    gated level down on every caller that scores from ``CrateState`` alone.
    """

    def _state(self):
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        return vhps_fixture_state("S-VHPS21")

    def test_graph_checks_return_none_without_a_graph(self):
        from builder.tools.fair_assessment import DSM_CHECKS

        graph_aware = [
            "tidy_dataset", "reference_fields", "local_data_dictionary",
            "local_dataset_model", "standard_field_names", "non_proprietary_format",
            "semantic_contextual_metadata", "common_data_elements",
        ]
        for name in graph_aware:
            assert DSM_CHECKS[name](self._state(), None) is None, name

    def test_an_unanswered_indicator_leaves_the_denominator(self):
        from builder.tools.fair_assessment import dsm_grid

        state = self._state()
        without = dsm_grid(state, None, None)
        # With no graph, the field/value indicators are unanswered, so the
        # denominator shrinks — it must never grow a failure instead.
        for level, by_cat in without.items():
            for cat, cell in by_cat.items():
                assert cell["passed"] <= cell["assessed"], (level, cat)

    def test_the_gated_level_is_not_dragged_down_by_a_missing_graph(self):
        """The regression this guards: scoring from CrateState alone must not fall."""
        from builder.tools.fair_assessment import assess_fair_maturity

        assert assess_fair_maturity(self._state()).dsm_level == 2


class TestTheQuestionnaireLadder:
    """The instrument's options nest by level, and the sheet resolves that by promoting.

    Within one question the statements form a ladder — "standardised to a *community*
    Standard Dataset Model" (L3) sits above "...to a *locally defined* Dataset Model"
    (L2) — so an option cannot honestly be true while a lower rung of the same
    question is false. The published sheet resolves that by PROMOTING the lower rung
    (``J4`` is ``=IF(J5=1,1,H4)``), and the scorer reproduces those nine rules rather
    than inventing a constraint of its own.
    """

    def _promoted(self, rules, checks, indicators):
        """Run the real scorer over a stub model and return its verdict map."""
        import unittest.mock as m

        from builder.tools import fair_assessment as fa

        data = {"indicators": indicators, "scoring": {"promotion": rules}}
        with m.patch.dict(fa.DSM_CHECKS, checks):
            return fa.dsm_verdicts(CrateStateStub(), data, None)

    def test_a_met_rung_promotes_the_one_below_it(self):
        """`J4` is `=IF(J5=1,1,H4)`: meeting DSM-3-R2 satisfies DSM-2-R2."""
        verdicts = self._promoted(
            [{"cell": "J4", "then": "A", "when": "B"}],
            {"no": lambda _s, _g=None: False, "yes": lambda _s, _g=None: True},
            [
                {"id": "A", "level": 2, "category": "C", "scope": "full", "check": "no"},
                {"id": "B", "level": 3, "category": "C", "scope": "full", "check": "yes"},
            ],
        )
        assert verdicts["A"].value is True, "the sheet promotes the lower rung"
        assert verdicts["B"].value is True
        assert "promoted by B" in verdicts["A"].evidence
        assert "J4" in verdicts["A"].evidence, "the evidence must name the sheet cell"

    def test_an_indicator_the_sheet_leaves_plain_is_never_rewritten(self):
        """Only nine pairs are linked. Every other J cell is a plain `=H{row}`, so two
        statements the sheet leaves independent must stay independent."""
        verdicts = self._promoted(
            [],
            {"no": lambda _s, _g=None: False, "yes": lambda _s, _g=None: True},
            [
                {"id": "A", "level": 2, "category": "C", "scope": "full", "check": "no"},
                {"id": "B", "level": 3, "category": "C", "scope": "full", "check": "yes"},
            ],
        )
        assert verdicts["A"].value is False
        assert verdicts["A"].evidence == ""

    def test_an_unanswered_source_does_not_promote(self):
        """`IF(blank=1,...)` is false — nothing is claimed on the strength of nothing."""
        verdicts = self._promoted(
            [{"cell": "J4", "then": "A", "when": "B"}],
            {"no": lambda _s, _g=None: False, "none": lambda _s, _g=None: None},
            [
                {"id": "A", "level": 2, "category": "C", "scope": "full", "check": "no"},
                {"id": "B", "level": 3, "category": "C", "scope": "full", "check": "none"},
            ],
        )
        assert verdicts["A"].value is False
        assert verdicts["B"].value is None

    def test_an_unanswered_target_is_promoted(self):
        """`IF(J5=1,1,H4)` returns 1 whatever H4 holds, including nothing at all.

        This is the behaviour that most distinguishes the sheet from a conservative
        reading: an indicator we never measured is satisfied by the rung above it.
        """
        verdicts = self._promoted(
            [{"cell": "J4", "then": "A", "when": "B"}],
            {"none": lambda _s, _g=None: None, "yes": lambda _s, _g=None: True},
            [
                {"id": "A", "level": 2, "category": "C", "scope": "full", "check": "none"},
                {"id": "B", "level": 3, "category": "C", "scope": "full", "check": "yes"},
            ],
        )
        assert verdicts["A"].value is True

    def test_promotion_chains_to_a_fixed_point(self):
        """`J10` reads `J11`, which reads `J12` — one sweep would stop halfway."""
        verdicts = self._promoted(
            [
                {"cell": "J10", "then": "A", "when": "B"},
                {"cell": "J11", "then": "B", "when": "C"},
            ],
            {"no": lambda _s, _g=None: False, "yes": lambda _s, _g=None: True},
            [
                {"id": "A", "level": 1, "category": "R", "scope": "full", "check": "no"},
                {"id": "B", "level": 2, "category": "R", "scope": "full", "check": "no"},
                {"id": "C", "level": 3, "category": "R", "scope": "full", "check": "yes"},
            ],
        )
        assert verdicts["A"].value is True, "the chain must run to a fixed point"
        assert verdicts["B"].value is True

    def test_promotion_never_manufactures_a_pass(self):
        """Every `True` traces to a check that answered True somewhere in its chain.

        This is what replaces the guarantee the old demotion pass was reaching for:
        promotion is monotone upward, so it can lift a verdict — but only ever on the
        evidence of a real check, never out of nothing.
        """
        for rule in _yaml()["scoring"]["promotion"]:
            verdicts = self._promoted(
                [rule],
                {"no": lambda _s, _g=None: False},
                [
                    {"id": rule["then"], "level": 1, "category": "R",
                     "scope": "full", "check": "no"},
                    {"id": rule["when"], "level": 2, "category": "R",
                     "scope": "full", "check": "no"},
                ],
            )
            assert verdicts[rule["then"]].value is False, rule["cell"]


class TestEveryVerdictCarriesItsEvidence:
    """A bare boolean cannot be audited; the model is a human assessment instrument."""

    def test_graph_checks_report_what_they_measured(self):
        import json

        from builder.tools.fair_assessment import dsm_verdicts

        crate = REPO / "output" / "svhps22_real_input_crate_v20" / "ro-crate-metadata.json"
        if not crate.is_file():
            import pytest

            pytest.skip("no built crate on disk to score")
        graph = json.loads(crate.read_text())["@graph"]
        verdicts = dsm_verdicts(CrateStateStub(), None, graph)
        measured = [v for v in verdicts.values() if v.evidence]
        assert measured, "no verdict carried evidence"
        # Evidence must be a measurement, not a restatement of the verdict.
        joined = " ".join(v.evidence for v in measured)
        assert any(ch.isdigit() for ch in joined), "evidence should quantify what was found"

    def test_verdict_refuses_truthiness(self):
        """Tri-state: `if verdict:` must not silently read None as False."""
        import pytest

        from builder.tools.fair_assessment import Verdict

        with pytest.raises(TypeError, match="tri-state"):
            bool(Verdict(None, ""))


def CrateStateStub():
    from builder.state import CrateState

    return CrateState()


# ---------------------------------------------------------------------------
# The sheet's own scoring definition
# ---------------------------------------------------------------------------

# The nine promotion rules, read off the "FAIR-DSM Assessment Sheet v1.2" validation
# column: J4 is `=IF(J5=1,1,H4)`, i.e. meeting DSM-3-R2 satisfies DSM-2-R2. Every other
# J cell is a plain `=H{row}`. The sheet promotes; it never demotes.
PUBLISHED_PROMOTION = {
    ("DSM-2-R2", "DSM-3-R2"),
    ("DSM-1-R3", "DSM-2-R3"),
    ("DSM-2-R3", "DSM-3-R3"),
    ("DSM-1-R1", "DSM-2-R1"),
    ("DSM-2-R1", "DSM-3-R1"),
    ("DSM-1-R4", "DSM-3-R4"),
    ("DSM-3-R4", "DSM-4-R4"),
    ("DSM-1-R5", "DSM-3-R5"),
    ("DSM-3-R5", "DSM-4-R5"),
}

# The sheet computes a "% Complete" grid of six levels x {C, R, H, Total}.
SHEET_GRID_CELLS = 24


def _superseded_by() -> dict[str, set[str]]:
    """The online assessment tool's own SUPERSEDED_BY column — a second authority."""
    wb = openpyxl.load_workbook(DSM_XLSX, read_only=True, data_only=True)
    ws = wb["Assessment Tool Data v1.2 "]
    rows = list(ws.iter_rows(values_only=True))
    header = [str(c).strip() if c else "" for c in rows[0]]
    col = {name: i for i, name in enumerate(header) if name}
    out: dict[str, set[str]] = {}
    for row in rows[1:]:
        ident = str(row[col["INDICATORID"]]).strip() if row[col["INDICATORID"]] else ""
        sup = row[col["SUPERSEDED_BY"]]
        if not ident.startswith("DSM-") or not sup:
            continue
        out[ident] = {s.strip() for s in str(sup).split(",") if s.strip()}
    return out


class TestTheSheetsOwnScoringIsCarried:
    """The YAML carries the workbook's arithmetic, so the scorer never invents its own.

    Without this block the tool has to hand-code the ladder, the grid membership and
    the denominators — which is how it came to demote where the sheet promotes, and to
    group each grid cell by the indicator's own level where the sheet carries lower
    levels forward.
    """

    def test_the_promotion_rules_are_the_sheets_own_nine(self):
        rules = _yaml()["scoring"]["promotion"]
        assert {(r["then"], r["when"]) for r in rules} == PUBLISHED_PROMOTION
        assert all(r["cell"].startswith("J") for r in rules)

    def test_promotion_agrees_with_the_online_tools_superseded_by(self):
        """Two authorities, one assertion: the offline sheet and the online tool data.

        The transitive closure of the sheet's IF-chain must equal the questionnaire
        sheet's own SUPERSEDED_BY column. They are maintained independently, so
        agreement is the strongest parity evidence the workbook can give.
        """
        direct: dict[str, set[str]] = {}
        for rule in _yaml()["scoring"]["promotion"]:
            direct.setdefault(rule["then"], set()).add(rule["when"])

        def closure(ident: str) -> set[str]:
            out: set[str] = set()
            stack = list(direct.get(ident, ()))
            while stack:
                node = stack.pop()
                if node in out:
                    continue
                out.add(node)
                stack.extend(direct.get(node, ()))
            return out

        assert {k: closure(k) for k in direct} == _superseded_by()

    def test_every_grid_cell_states_its_members_and_denominator(self):
        cells = _yaml()["scoring"]["grid"]
        assert len(cells) == SHEET_GRID_CELLS
        known = {i["id"] for i in _yaml()["indicators"]}
        for cell in cells:
            if "constant" in cell:
                assert not cell["members"], f"{cell['cell']} is a constant, not a count"
                continue
            assert set(cell["members"]) <= known, f"{cell['cell']} names an unknown id"
            assert len(cell["members"]) == cell["denominator"]["n"], (
                f"{cell['cell']}: the sheet's denominator must equal its member count — "
                "column J is all formulas, so a blank scores 0 rather than dropping out"
            )

    def test_a_level_cell_carries_lower_levels_forward(self):
        """The sheet's L2 Content cell counts two Level-1 indicators; ours must too."""
        by_cell = {c["cell"]: c for c in _yaml()["scoring"]["grid"]}
        assert {"DSM-1-C2", "DSM-1-C3"} <= set(by_cell["P14"]["members"])

    def test_the_total_column_is_the_union_of_the_three_categories(self):
        grid = _yaml()["scoring"]["grid"]
        by_level: dict[int, dict[str, list[str]]] = {}
        for cell in grid:
            by_level.setdefault(cell["level"], {})[cell["category"]] = cell["members"]
        for level, cats in by_level.items():
            union = set(cats.get("C", [])) | set(cats.get("R", [])) | set(cats.get("H", []))
            assert union == set(cats.get("TOTAL", [])), f"level {level} total drifted"

    def test_only_level_zero_counts_zeros(self):
        """Level 0 states the pre-FAIRification condition, so the sheet counts its 0s."""
        for cell in _yaml()["scoring"]["grid"]:
            if "constant" in cell:
                continue
            assert cell["counts"] == (0 if cell["level"] == 0 else 1), cell["cell"]

    def test_a_member_listed_twice_is_counted_twice(self):
        """P24 names DSM-4-H2 on two rows; deduping would change the denominator."""
        by_cell = {c["cell"]: c for c in _yaml()["scoring"]["grid"]}
        assert by_cell["P24"]["members"].count("DSM-4-H2") == 2
        assert by_cell["P24"]["denominator"]["n"] == 3

    def test_indicators_on_no_assessment_row_are_named_not_dropped(self):
        """DSM-2-R5 is scored locally but appears in no published cell — say so."""
        data = _yaml()
        in_a_cell = {m for c in data["scoring"]["grid"] for m in c["members"]}
        off_sheet = set(data["scoring"]["off_sheet"])
        assert "DSM-2-R5" in off_sheet
        assert not (off_sheet & in_a_cell)
        scoped = {i["id"] for i in data["indicators"] if i["scope"] != "na"}
        assert scoped - in_a_cell == {"DSM-2-R5"}

class TestTheLadderIsReportedAsTheToolReportsIt:
    """The published tool prints a per-level checklist — "N indicators still need to be
    satisfied for your Datasets to reach Maturity Level X" — listing every indicator
    that level counts, the lower ones it carries forward included, each identified.
    Reproducing that is what lets a reader check this report against a run of the tool.
    """

    def _page(self):
        from builder.writers.maturity_report import build_maturity_html
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        return build_maturity_html(vhps_fixture_state("S-VHPS21"))

    def test_level_zero_is_reported_nowhere(self):
        """The tool's own output runs Level 1 to 5. Level 0 states the pre-FAIRification
        condition in the negative and is scored by counting zeros, so an unanswered row
        reads 100% — "fully escaped", on the strength of nobody having looked."""
        page = self._page()
        assert "Single-use data" not in page, "the Level-0 row must not be rendered"
        for level in range(1, 6):
            assert f"Maturity Level {level}" in page

    def test_each_level_lists_exactly_what_the_sheet_counts(self):
        """Including the lower levels it carries forward, and including a member the
        sheet lists twice — the tool prints DSM-4-H2 twice at Level 4 and divides by 3."""
        data = _yaml()
        cells = {(c["level"], c["category"]): c for c in data["scoring"]["grid"]}
        page = self._page()
        section = page[page.index('id="ladder"') :].split("</section>", 1)[0]
        blocks = re.findall(r'<div class="lvlblock">.*?</ul>', section, re.S)
        assert len(blocks) == 5, "one block per level, 1 to 5"
        for level, block in zip(range(1, 6), blocks, strict=True):
            members = cells[(level, "TOTAL")]["members"]
            ids = re.findall(r"#(dsm-[0-9]-[a-z][0-9])", block)
            assert [i.upper() for i in ids] == [m.upper() for m in members], level

    def test_an_indicator_nothing_measured_is_neither_met_nor_failed(self):
        """The tool has two states because a person answers everything; this has three.
        Counting an unassessed hosting indicator as failed asserts a verdict nothing
        reached."""
        page = self._page()
        section = page[page.index('id="ladder"') :].split("</section>", 1)[0]
        assert 'class="lvl-unknown"' in section, "no unassessed state rendered"
        assert "not yet assessed" in section, "the count must name them"
        # every hosting indicator is unassessable from a crate, so none may read as met
        for block in re.findall(r'<li class="lvl-(\w+)">.*?#(dsm-[0-9]-h[0-9])', section):
            assert block[0] != "met", block[1]

    def test_every_indicator_links_to_the_models_own_definition(self):
        page = self._page()
        found = set(
            re.findall(
                r"https://fairplus\.github\.io/Data-Maturity/docs/Indicators/#([a-z0-9-]+)",
                page,
            )
        )
        known = {i["id"].lower() for i in _yaml()["indicators"]}
        assert found and found <= known, f"unknown ids linked: {found - known}"
        assert "dsm-1-h1" in found, "the hosting statements must link out too"
