"""Issue #356: the generic FAIR indicators are DERIVED from the vendored RDA FAIR
Data Maturity Model (``fair/rda_fdmm.xlsx``), not hand-authored.

``fair/indicators.yaml`` is generated by ``scripts/gen_fair_indicators.py`` from the
RDA XLSX (definitions: dimension / priority / text) plus a local scope/check map
(which indicators are assessed intrinsically, and with which check). These tests pin
that contract so the definitions can never silently drift from RDA, while the local
scoring logic — and therefore the scores — stay put.
"""

from __future__ import annotations

import importlib.util
import pathlib

import openpyxl
import pytest
import yaml

from builder.state import CrateState

REPO = pathlib.Path(__file__).resolve().parents[1]
INDICATORS_YAML = REPO / "fair" / "indicators.yaml"
RDA_XLSX = REPO / "fair" / "rda_fdmm.xlsx"
GEN = REPO / "scripts" / "gen_fair_indicators.py"


def _yaml_data() -> dict:
    """The committed indicators.yaml."""
    return yaml.safe_load(INDICATORS_YAML.read_text())


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_fair_indicators", GEN)
    # Checked BEFORE module_from_spec, which cannot take None — the assert used
    # to sit after the call it was meant to guard.
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _rda_rows() -> dict[str, dict[str, str]]:
    """The canonical RDA indicator definitions, straight from the vendored XLSX."""
    wb = openpyxl.load_workbook(RDA_XLSX, read_only=True, data_only=True)
    ws = wb["FAIR Indicators_v0.05"]
    out: dict[str, dict[str, str]] = {}
    for row in list(ws.iter_rows(values_only=True))[1:]:
        iid = row[4]
        if iid and str(iid).startswith("RDA-"):
            out[str(iid)] = {
                "dimension": str(row[3])[0],  # PRINCIPLE (e.g. "F1") -> "F"
                "priority": str(row[6]).strip().lower(),
                "text": str(row[5]).strip(),
            }
    return out


# The published model, as distributed in the vendored RDA spreadsheet.
PUBLISHED_TOTAL = 41
PUBLISHED_PER_PRIORITY = {"essential": 20, "important": 14, "useful": 7}


class TestTheProvenanceIsCitable:
    """A reader must be able to get from this file to the actual works, correctly.

    These are offline pins on values verified live against Crossref, DataCite and
    Zenodo — a citation nobody has resolved is a citation nobody should trust.
    """

    def test_the_specification_and_the_paper_are_not_conflated(self):
        """They are two works. One `citation` beside one `doi` made them look like one.

        `10.15497/rda00050` is the RDA deliverable and has no authors; Bahim et al. is
        a separate peer-reviewed article. Quoting the author list against the
        deliverable's DOI produces a reference that does not resolve to what it names.
        """
        rda = yaml.safe_load(INDICATORS_YAML.read_text())["sources"]["rda"]
        assert rda["specification"]["doi"] == "10.15497/rda00050"
        assert rda["peer_reviewed"]["doi"] == "10.5334/dsj-2020-041"
        assert rda["specification"]["doi"] != rda["peer_reviewed"]["doi"]
        assert "Bahim" in rda["peer_reviewed"]["citation"]
        assert "Bahim" not in str(rda["specification"])

    def test_the_specification_is_attributed_to_the_alliance_not_to_authors(self):
        rda = yaml.safe_load(INDICATORS_YAML.read_text())["sources"]["rda"]
        assert rda["specification"]["publisher"] == "Research Data Alliance"
        assert "author" not in rda["specification"]

    def test_the_vendored_workbook_is_the_published_file(self):
        """Byte-identical to Zenodo record 3909563's FAIR_evaluation_levels_v0.02.xlsx.

        Checked live once; pinned here so a re-vendoring that silently substitutes a
        different or edited workbook fails rather than quietly changing what the
        indicator definitions say.
        """
        import hashlib

        assert (
            hashlib.md5(RDA_XLSX.read_bytes()).hexdigest()
            == "b6231346dff874a3675747ab3e295fd9"
        )
        assert RDA_XLSX.stat().st_size == 195824

    def test_the_licence_is_the_one_the_publisher_states(self):
        rda = yaml.safe_load(INDICATORS_YAML.read_text())["sources"]["rda"]
        assert rda["license"] == "CC-BY-4.0"


class TestTheWholePublishedModelIsCarried:
    """All 41 indicators, including the ones this tool cannot answer.

    The DSM and Bridge2AI files carry every published item and mark what they cannot
    assess. This one used to carry 21 and simply omit the other 20, so "14 of 21 met"
    read as coverage of the model when it was really 14 of 41 with 20 never asked.
    An instrument you report against is one you have to reproduce in full; which parts
    we answer is a local decision that must be visible, not implied by absence.
    """

    def test_every_published_indicator_is_present(self):
        committed = yaml.safe_load(INDICATORS_YAML.read_text())["indicators"]
        assert len(committed) == PUBLISHED_TOTAL
        assert {i["id"] for i in committed} == set(_rda_rows())

    def test_the_priority_split_is_the_published_one(self):
        from collections import Counter

        committed = yaml.safe_load(INDICATORS_YAML.read_text())["indicators"]
        assert dict(Counter(i["priority"] for i in committed)) == PUBLISHED_PER_PRIORITY

    def test_the_useful_tier_is_no_longer_missing_entirely(self):
        """All 7 `useful` indicators were absent — a whole priority tier unasked."""
        committed = yaml.safe_load(INDICATORS_YAML.read_text())["indicators"]
        assert sum(1 for i in committed if i["priority"] == "useful") == 7

    def test_every_unassessed_indicator_says_why(self):
        """"Not assessed" without a reason is indistinguishable from an oversight."""
        committed = yaml.safe_load(INDICATORS_YAML.read_text())["indicators"]
        unscored = [i for i in committed if i.get("scope") == "out_of_scope"]
        assert unscored
        for ind in unscored:
            assert ind.get("reason"), f"{ind['id']} is out of scope with no reason given"
            assert "check" not in ind, f"{ind['id']} is out of scope but names a check"

    def test_every_scored_indicator_names_a_registered_check(self):
        from builder.tools.fair_assessment import FAIR_CHECKS

        committed = yaml.safe_load(INDICATORS_YAML.read_text())["indicators"]
        for ind in committed:
            if ind.get("scope") != "out_of_scope":
                assert ind["check"] in FAIR_CHECKS, f"{ind['id']} names an unknown check"

    def test_the_generator_refuses_an_id_the_model_does_not_define(self):
        gen = _load_generator()
        gen.LOCAL_SCOPE["RDA-NOPE-01M"] = ("check", None)
        try:
            with pytest.raises(KeyError, match="not an RDA"):
                gen.build_data()
        finally:
            gen.LOCAL_SCOPE.pop("RDA-NOPE-01M", None)

    def test_the_report_states_what_is_asked_and_what_is_not(self):
        gen = _load_generator()
        report = gen.format_report(gen.build_data())
        assert "41" in report
        assert "out of scope" in report.lower()


class TestFairIndicatorsDerivedFromRda:
    def test_indicators_yaml_matches_generator_output(self):
        """The committed indicators.yaml is exactly what the generator emits from the
        RDA XLSX + the local scope map — no hand drift."""
        gen = _load_generator()
        committed = yaml.safe_load(INDICATORS_YAML.read_text())
        assert committed["indicators"] == gen.build_data()["indicators"]

    def test_every_indicator_matches_rda_definition(self):
        """Every indicator id exists in the RDA model, and its dimension / priority /
        text are the RDA values (definitions sourced from RDA, not hand-typed)."""
        rda = _rda_rows()
        committed = yaml.safe_load(INDICATORS_YAML.read_text())
        assert committed["indicators"], "no indicators loaded"
        for ind in committed["indicators"]:
            iid = ind["id"]
            assert iid in rda, f"{iid} is not an RDA FAIR Data Maturity Model indicator"
            assert ind["dimension"] == rda[iid]["dimension"], iid
            assert ind["priority"] == rda[iid]["priority"], iid
            assert ind["text"] == rda[iid]["text"], iid

    def test_fair_scores_for_golden_crate(self):
        """The per-indicator pin for S-VHPS21, scored the way production scores it.

        Was ``test_fair_scores_unchanged_for_golden_crate``, asserting that re-sourcing
        the definitions moved no verdict. #670 moves verdicts on purpose, so the pin
        is re-derived rather than defended, and the assessment now runs against the
        assembled ``@graph`` — which is what both production callers pass, and the only
        input a reader of the published crate has.

        Two verdicts changed, both downwards, both for a stated reason:

        * ``RDA-F1-02D`` True -> **False**. "Data is identified by a globally unique
          identifier": the crate's Files carry crate-relative paths and the root mints
          no DOI for them to compose against. The old check asked whether every
          ``Entity`` had an ``entity_id``, which nothing in the crate can falsify.
        * ``RDA-R1-01M`` True -> **False**. "Plurality of accurate and relevant
          attributes": the root declares no licence — one of the four RO-Crate requires
          — and 1 of its 4 subjects is described beyond a bare name. The old check was
          ``len(state.list_entities()) >= 2``.

        13 met / 5 failed -> **11 met / 7 failed**. ``dsm_level`` 2 -> **0** once the
        DSM half of #670 landed: the ladder must never rise when checks move to the
        graph, and here it falls, because this crate's only payload file is one the
        builder minted. The four Level-1 blockers are named beside the assertion below.
        """
        from builder.tools.fair_assessment import assess_fair_maturity
        from builder.tools.mit_assessment import _assemble_graph
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        state = vhps_fixture_state("S-VHPS21")
        rep = assess_fair_maturity(state, graph={"@graph": _assemble_graph(state) or []})
        got = {r["id"]: (r.get("passed"), r.get("scope", "")) for r in rep.indicator_results}
        expected = {
            "RDA-F1-02M": (False, ""),
            "RDA-F1-02D": (False, ""),
            "RDA-F1-01M": (False, ""),
            "RDA-F2-01M": (True, ""),
            "RDA-F3-01M": (True, ""),
            "RDA-A1-02M": (None, "out_of_scope"),
            "RDA-A1-04D": (None, "out_of_scope"),
            "RDA-A2-01M": (None, "out_of_scope"),
            "RDA-I1-01M": (True, ""),
            "RDA-I1-02M": (True, ""),
            "RDA-I2-01M": (True, ""),
            "RDA-I3-01M": (True, ""),
            "RDA-I3-03M": (True, ""),
            "RDA-R1-01M": (False, ""),
            "RDA-R1.1-01M": (False, ""),
            "RDA-R1.1-02M": (False, ""),
            "RDA-R1.1-03M": (False, ""),
            "RDA-R1.2-01M": (True, ""),
            "RDA-R1.3-01M": (True, ""),
            "RDA-R1.3-02M": (True, ""),
            "RDA-R1.3-01D": (False, ""),
        }
        # Carrying the whole model adds 20 indicators this tool does not answer. They
        # report "not assessed" and must not move a single verdict above.
        expected.update(
            {
                iid: (None, "out_of_scope")
                for iid in (
                    "RDA-F1-01D", "RDA-F4-01M", "RDA-A1-01M", "RDA-A1-02D",
                    "RDA-A1-03M", "RDA-A1-03D", "RDA-A1-04M", "RDA-A1-05D",
                    "RDA-A1.1-01M", "RDA-A1.1-01D", "RDA-A1.2-01D", "RDA-I1-01D",
                    "RDA-I1-02D", "RDA-I2-01D", "RDA-I3-01D", "RDA-I3-02M",
                    "RDA-I3-02D", "RDA-I3-04M", "RDA-R1.2-02M", "RDA-R1.3-02D",
                )
            }
        )
        assert got == expected
        # DSM 0, down from 2 before #670's DSM rewrite. The golden crate's only payload
        # file is a builder-minted condition table, so the three Level-1 indicators that
        # ask about *the data* (DSM-1-C2, DSM-1-R2, DSM-1-R5) now fail, and DSM-1-C0
        # fails because nothing mints a persistent identifier for the root. The number
        # went down because the checks stopped scoring the session; see
        # tests/test_fair_metrics_can_fail.py for the corpus-wide measurement.
        assert rep.dsm_level == 0

    def test_widening_the_model_did_not_move_the_score(self):
        """The met count is a property of the crate, not of how many we ask."""
        from builder.tools.fair_assessment import assess_fair_maturity
        from builder.tools.mit_assessment import _assemble_graph
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        state = vhps_fixture_state("S-VHPS21")
        rep = assess_fair_maturity(state, graph={"@graph": _assemble_graph(state) or []})
        met = sum(1 for r in rep.indicator_results if r.get("passed") is True)
        failed = sum(1 for r in rep.indicator_results if r.get("passed") is False)
        # 10/8 since #712: F1-02M asks the crate for a globally unique identifier
        # instead of reading `session_id`, and this crate carries none. 11/7 before
        # that, 13/5 before #670 (F1-02D and R1-01M fail for stated reasons).
        # R1.3-01D reads False here because no MIT report is passed.
        assert (met, failed) == (10, 8), "the verdicts moved; only the denominator should"
        assert len(rep.indicator_results) == 41, "the whole model is reported"

    def test_the_graph_is_what_makes_the_score_answerable(self):
        """#670: eleven indicators read the crate, so state alone cannot answer them.

        Not a redundant restatement of the pin above — it fixes *which* input the
        number belongs to. A caller passing no graph gets "not assessed" for those
        eleven, and 3 met is a smaller, honest claim rather than the same claim guessed
        from a session object no reader receives. RDA-F1-02M joined them in #712: it
        used to answer True from `session_id`, which is neither the crate nor an
        identifier anyone receives.
        """
        from builder.tools.fair_assessment import assess_fair_maturity
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        rep = assess_fair_maturity(vhps_fixture_state("S-VHPS21"))
        met = sum(1 for r in rep.indicator_results if r.get("passed") is True)
        in_scope_unanswered = sum(
            1
            for r in rep.indicator_results
            if r.get("passed") is None and r.get("scope") != "out_of_scope"
        )
        assert (met, in_scope_unanswered) == (3, 11)


class TestTheWorkbooksOwnScoringIsRecorded:
    """The RDA workbook computes something, and this tool computes something else.

    Until #715 the YAML carried no `scoring` block at all, so the substitution was
    visible only as a missing key — and the generator's stated reason (third-party
    evaluators need a resolvable URL) is about services, not about the instrument
    vendored beside it. The block now records what the sheet does, read from its own
    cells, and these tests are what keep the record true.
    """

    @staticmethod
    def _sheet(name: str):
        return openpyxl.load_workbook(RDA_XLSX, data_only=False)[name]

    def test_the_per_indicator_formula_is_the_workbooks(self) -> None:
        """Not a hand-copied literal: byte-for-byte the cell it names."""
        block = _yaml_data()["scoring"]["per_indicator"]
        assert block["formula"] == self._sheet("FAIR Indicators_v0.05")["J2"].value

    def test_the_ladder_formula_is_the_workbooks(self) -> None:
        block = _yaml_data()["scoring"]["ladder"]
        assert block["formula"] == self._sheet("calc")["C13"].value

    def test_the_level_definitions_are_the_workbooks_own_words(self) -> None:
        levels = _yaml_data()["scoring"]["ladder"]["levels"]
        sheet = self._sheet("LEVELS")
        assert [lvl["definition"] for lvl in levels] == [
            sheet.cell(row=r, column=5).value for r in range(5, 11)
        ]
        assert levels[0]["definition"] == "Not FAIR"

    def test_our_boolean_is_the_sheets_own_column_not_a_coarsening(self) -> None:
        """The sheet's native answer is a five-way metric, and it collapses it itself:
        column J scores 1 only for "fully implemented" and 0 for every partial state
        and for a blank. So met/failed is the instrument's, and the `scoring` block
        must not claim otherwise."""
        scoring = _yaml_data()["scoring"]
        assert len(scoring["metric"]) == 5, "the published metric is 0-4"
        formula = scoring["per_indicator"]["formula"]
        assert formula.endswith(",0,1)"), "1 only when none of the sub-4 states match"
        assert "$H2=0" in formula, "a blank scores 0 — the sheet has no unanswered state"

    def test_the_deviation_note_measures_what_it_claims(self) -> None:
        """The note says the ladder would report the repository's properties as the
        crate's failure. That rests on two counts over the model as carried, and if
        either changes the note is wrong and must be rewritten."""
        data = _yaml_data()
        by_dim: dict[str, list[dict]] = {}
        for ind in data["indicators"]:
            by_dim.setdefault(ind["dimension"], []).append(ind)
        out = {
            dim: [i for i in inds if i.get("scope") == "out_of_scope"]
            for dim, inds in by_dim.items()
        }
        assert len(out["A"]) == len(by_dim["A"]) == 12, "Accessibility is wholly out of scope"
        f_essential = [i["id"] for i in out["F"] if i["priority"] == "essential"]
        assert sorted(f_essential) == ["RDA-F1-01D", "RDA-F4-01M"], (
            "Findability's two out-of-scope essentials are what put Level 1 out of reach"
        )
        note = data["scoring"]["deviation_note"]
        assert "12 of 12" in note and "RDA-F1-01D" in note

    def test_no_level_is_published(self) -> None:
        """The declaration has to match the code: this tool reports counts, not levels."""
        from builder.tools.fair_assessment import assess_fair_maturity

        rep = assess_fair_maturity(CrateState())
        assert not hasattr(rep, "area_levels") and not hasattr(rep, "rda_level")
        assert _yaml_data()["scoring"]["local_output"].startswith("a met / failed")
