"""The DSM indicators are DERIVED from the vendored FAIRplus assessment workbook
(``fair/fairplus_dsm_v1.2.xlsx``), not hand-authored.

``fair/dsm_indicators.yaml`` is generated by ``scripts/gen_dsm_indicators.py`` from the
workbook's "MASTER (Levels View)" sheet (definitions: level / category / verbatim text /
granularity / the model's own RDA + FAIRsFAIR cross-references) plus a local scope/check
map. These tests pin that contract so the published model can never silently drift into a
paraphrase, and so the paper's claim to be scoring *the FAIRplus DSM* stays true.

The prior hand-curated file carried 28 entries — 25 of the 83 published indicators, one
invented id (``DSM-5``), paraphrased text, and level names found nowhere in the model.
"""

from __future__ import annotations

import importlib.util
import pathlib

import openpyxl
import yaml

REPO = pathlib.Path(__file__).resolve().parents[1]
DSM_YAML = REPO / "fair" / "dsm_indicators.yaml"
DSM_XLSX = REPO / "fair" / "fairplus_dsm_v1.2.xlsx"
GEN = REPO / "scripts" / "gen_dsm_indicators.py"

# The published model, as distributed in v1.2 of the assessment sheet.
PUBLISHED_TOTAL = 83
PUBLISHED_PER_LEVEL = {0: 11, 1: 14, 2: 15, 3: 16, 4: 14, 5: 13}
PUBLISHED_PER_CATEGORY = {"C": 31, "R": 32, "H": 20}


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_dsm_indicators", GEN)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _yaml() -> dict:
    return yaml.safe_load(DSM_YAML.read_text())


def _workbook_rows() -> dict[str, dict]:
    """Indicator id -> row, read straight from the vendored workbook."""
    wb = openpyxl.load_workbook(DSM_XLSX, read_only=True, data_only=True)
    ws = wb["MASTER (Levels View)"]
    out: dict[str, dict] = {}
    level = None
    for row in list(ws.iter_rows(values_only=True))[1:]:
        if row[0] not in (None, ""):
            try:
                level = int(float(row[0]))
            except (TypeError, ValueError):
                pass
        ident = str(row[2]).strip() if row[2] else ""
        if not ident.startswith("DSM-"):
            continue
        out[ident] = {
            "level": level,
            "text": str(row[4]).strip() if row[4] else "",
            "granularity": str(row[7]).strip() if row[7] else "",
        }
    return out


class TestGeneratedFromTheWorkbook:
    """The committed YAML is exactly what the generator produces from the workbook."""

    def test_committed_yaml_equals_generator_output(self):
        mod = _load_generator()
        assert _yaml() == mod.build_data(), (
            "fair/dsm_indicators.yaml is stale or hand-edited — "
            "regenerate with `uv run python scripts/gen_dsm_indicators.py`"
        )

    def test_the_vendored_workbook_is_present(self):
        assert DSM_XLSX.is_file() and DSM_XLSX.stat().st_size > 100_000


class TestTheWholePublishedModelIsCarried:
    """All 83 indicators, not the subset we happen to assess."""

    def test_every_published_indicator_is_present(self):
        ids = {i["id"] for i in _yaml()["indicators"]}
        assert ids == set(_workbook_rows())
        assert len(ids) == PUBLISHED_TOTAL

    def test_counts_per_level_and_category(self):
        inds = _yaml()["indicators"]
        per_level: dict[int, int] = {}
        per_cat: dict[str, int] = {}
        for i in inds:
            per_level[i["level"]] = per_level.get(i["level"], 0) + 1
            per_cat[i["category"]] = per_cat.get(i["category"], 0) + 1
        assert per_level == PUBLISHED_PER_LEVEL
        assert per_cat == PUBLISHED_PER_CATEGORY

    def test_indicator_text_is_verbatim_never_paraphrased(self):
        rows = _workbook_rows()
        for ind in _yaml()["indicators"]:
            src = rows[ind["id"]]
            assert ind["text"] == src["text"], f"{ind['id']} text drifted from the model"
            assert ind["level"] == src["level"], f"{ind['id']} level drifted"
            assert ind["granularity"] == src["granularity"], f"{ind['id']} granularity drifted"

    def test_no_invented_identifiers_survive(self):
        """The old file carried a bare ``DSM-5`` placeholder that the model never defined."""
        ids = {i["id"] for i in _yaml()["indicators"]}
        assert "DSM-5" not in ids
        # Every id is <model>-<level>-<category><n>, so a bare level id cannot recur.
        for iid in ids:
            assert iid.count("-") >= 2, f"{iid} is not a published DSM identifier"


class TestLevelNamesComeFromTheModel:
    """The old file named the levels after organisational tiers the model never uses."""

    def test_level_names_are_the_models_state_of_data(self):
        assert _yaml()["levels"] == {
            0: "Single-use data",
            1: "Identifiable Data",
            2: "Described Data",
            3: "Standardised Data",
            4: "Semantically Typed Data",
            5: "Managed Data Assets",
        }

    def test_the_invented_organisational_names_are_gone(self):
        text = DSM_YAML.read_text()
        for invented in ("Individual researcher", "Consortium", "Institutional data commons"):
            assert invented not in text, f"stale level name {invented!r} survives"


class TestLocalScopeIsHonest:
    """What we assess is declared per indicator, and never inflated."""

    def test_every_scoped_indicator_names_a_registered_check(self):
        from builder.tools.fair_assessment import DSM_CHECKS

        for ind in _yaml()["indicators"]:
            if ind["scope"] == "na":
                assert "check" not in ind, f"{ind['id']} is na but names a check"
                continue
            assert ind.get("check") in DSM_CHECKS, (
                f"{ind['id']} is scoped {ind['scope']!r} but its check "
                f"{ind.get('check')!r} is not registered in DSM_CHECKS"
            )

    def test_hosting_indicators_are_never_claimed_as_assessable(self):
        """A crate on disk cannot evidence its hosting environment's capabilities."""
        for ind in _yaml()["indicators"]:
            if ind["category"] == "H":
                assert ind["scope"] == "na", f"{ind['id']} is a hosting indicator"

    def test_level_zero_is_never_scored(self):
        """Level 0 states the pre-FAIR condition in the negative; passing it is bad."""
        for ind in _yaml()["indicators"]:
            if ind["level"] == 0:
                assert ind["scope"] == "na", f"{ind['id']} is a Level-0 negative state"

    def test_the_model_s_own_rda_cross_references_are_carried(self):
        """27 indicators cite an RDA indicator — the published bridge between the axes."""
        linked = [i for i in _yaml()["indicators"] if i.get("rda_ref")]
        assert len(linked) == 27
        assert all(i["rda_ref"].startswith(("RDA-", "[")) for i in linked)


class TestProvenanceIsRecorded:
    """The paper cites this file; it must say where it came from."""

    def test_source_block_names_the_distribution_and_licence(self):
        src = _yaml()["source"]
        assert src["version"] == "1.2"
        # The MODEL is CC BY 4.0. The repo's MIT LICENSE.txt covers only its Jekyll
        # theme; recording MIT here would under-attribute a work the paper cites.
        assert src["license"] == "CC-BY-4.0"
        assert src["specification"]["doi"] == "10.5281/zenodo.7464523"
        assert src["peer_reviewed"]["doi"] == "10.1038/s41597-023-02167-2"
        assert "FAIRplus" in src["name"] and "Dataset Maturity" in src["name"]
        assert "fairplus_dsm_v1.2.xlsx" in src["distribution"]
        assert src["repository"] == "https://github.com/FAIRplus/Data-Maturity"

    def test_it_records_that_the_model_assesses_a_dataset(self):
        """Guards the misreading that DSM scores an organisation's capability."""
        assert "DATASET, not an organisation" in _yaml()["source"]["note"]


class TestTheGeneratorRefusesToLie:
    """The generator fails loudly rather than scoring something that is not there."""

    def test_unknown_indicator_in_local_scope_raises(self):
        mod = _load_generator()
        original = dict(mod.LOCAL_SCOPE)
        mod.LOCAL_SCOPE["DSM-9-C9"] = ("full", "unique_id")
        try:
            with __import__("pytest").raises(KeyError, match="absent from the workbook"):
                mod.build_data()
        finally:
            mod.LOCAL_SCOPE.clear()
            mod.LOCAL_SCOPE.update(original)


class TestTheReport:
    """`gen_dsm_indicators.py` prints a per-level coverage summary (user request)."""

    def test_report_states_coverage_per_level(self):
        mod = _load_generator()
        report = mod.format_report(mod.build_data())
        assert "FAIRplus Dataset Maturity Model (DSM) v1.2" in report
        for name in ("Single-use data", "Identifiable Data", "Managed Data Assets"):
            assert name in report
        assert "hosting-environment" in report
        assert "83" in report


class TestTheModelsOwnPercentCompleteGrid:
    """`dsm_grid` reproduces the assessment sheet's 6x3 "% Complete" scoring.

    The sheet's formula, verbatim from cell P10 (Level 1, Content and context)::

        =(((COUNTIFS(J32,1))+(COUNTIFS(J45,1))+(COUNTIFS(J50,1))+(COUNTIFS(J51,1)))
          /(COUNT(J32,J45,J50,J51))*100)

    and P6 (Level 0), which counts ZEROS rather than ones::

        =(((COUNTIFS(J31,0))+(COUNTIFS(J44,0))+(COUNTIFS(J49,0)))/(COUNT(J31,J44,J49))*100)
    """

    def _grid(self):
        from builder.tools.fair_assessment import dsm_grid
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        return dsm_grid(vhps_fixture_state("S-VHPS21"))

    def test_the_grid_covers_every_published_level_and_category(self):
        grid = self._grid()
        assert set(grid) == set(PUBLISHED_PER_LEVEL)
        for level, by_cat in grid.items():
            assert set(by_cat) <= {"C", "R", "H"}, level
            assert sum(c["total"] for c in by_cat.values()) == PUBLISHED_PER_LEVEL[level]

    def test_percentage_is_over_what_was_assessed_not_what_exists(self):
        """The sheet's denominator is Excel COUNT, which omits unanswered cells.

        An indicator we cannot assess is an unanswered cell: it must not count
        against the dataset, or every percentage would be diluted by the 20
        hosting indicators no crate can ever evidence.
        """
        for by_cat in self._grid().values():
            for cell in by_cat.values():
                assert cell["assessed"] <= cell["total"]
                if cell["assessed"]:
                    expected = round(cell["passed"] / cell["assessed"] * 100, 1)
                    assert cell["pct"] == expected
                    assert cell["passed"] <= cell["assessed"]

    def test_an_unassessable_cell_is_none_never_zero(self):
        """`#DIV/0!` in the sheet — "not assessed" is not the same claim as 0%."""
        grid = self._grid()
        for level in (0, 5):
            for cell in grid[level].values():
                assert cell["assessed"] == 0
                assert cell["pct"] is None
        for by_cat in grid.values():
            hosting = by_cat.get("H")
            if hosting:
                assert hosting["pct"] is None, "no crate can evidence its hosting environment"

    def test_level_zero_is_scored_inverted(self):
        """Level 0 counts ZEROS (P6). Satisfying "data is NOT identifiable" is bad.

        Driven through the real scorer rather than asserted structurally: a
        level-0 indicator wired to a check that PASSES must score 0 there, which
        is the opposite of every other level.
        """
        from builder.tools import fair_assessment as fa
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        data = {
            "indicators": [
                {"id": "DSM-0-C0", "level": 0, "category": "C",
                 "scope": "full", "check": "unique_id"},
                {"id": "DSM-1-C0", "level": 1, "category": "C",
                 "scope": "full", "check": "unique_id"},
            ]
        }
        state = vhps_fixture_state("S-VHPS21")
        assert fa.DSM_CHECKS["unique_id"](state, None) is True
        grid = fa.dsm_grid(state, data)
        assert grid[0]["C"]["passed"] == 0, "a satisfied Level-0 negative must not score"
        assert grid[1]["C"]["passed"] == 1, "the same check at Level 1 must score"

    def test_the_report_renders_the_grid_faithfully(self):
        from builder.writers.maturity_report import build_maturity_html
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        page = build_maturity_html(vhps_fixture_state("S-VHPS21"))
        assert "DSM &mdash; % complete by level and category" in page
        # Every published level name is a row label.
        for name in _yaml()["levels"].values():
            assert name in page
        # An unassessable cell says so rather than showing a zero.
        assert "not assessed" in page
        # The deviation from the sheet is stated, not implied.
        assert "excluded from the denominator" in page
        assert "scored inverted" in page


class TestNoGraphMeansUnanswered:
    """A graph-aware check with no graph answers ``None``, never ``False``.

    The DSM's Level 2-4 field/value indicators live in the assembled ``@graph``.
    Answering ``False`` when no graph was supplied would read as "the crate fails
    this indicator" when the truth is "nothing was assessed" — and it would drag the
    gated level down on every caller that scores from ``CrateState`` alone.
    """

    def _state(self):
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        return vhps_fixture_state("S-VHPS21")

    def test_graph_checks_return_none_without_a_graph(self):
        from builder.tools.fair_assessment import DSM_CHECKS

        graph_aware = [
            "tidy_dataset", "reference_fields", "local_data_dictionary",
            "local_dataset_model", "standard_field_names", "non_proprietary_format",
            "semantic_contextual_metadata", "common_data_elements",
        ]
        for name in graph_aware:
            assert DSM_CHECKS[name](self._state(), None) is None, name

    def test_an_unanswered_indicator_leaves_the_denominator(self):
        from builder.tools.fair_assessment import dsm_grid

        state = self._state()
        without = dsm_grid(state, None, None)
        # With no graph, the field/value indicators are unanswered, so the
        # denominator shrinks — it must never grow a failure instead.
        for level, by_cat in without.items():
            for cat, cell in by_cat.items():
                assert cell["passed"] <= cell["assessed"], (level, cat)

    def test_the_gated_level_is_not_dragged_down_by_a_missing_graph(self):
        """The regression this guards: scoring from CrateState alone must not fall."""
        from builder.tools.fair_assessment import assess_fair_maturity

        assert assess_fair_maturity(self._state()).dsm_level == 2


class TestTheQuestionnaireLadder:
    """The instrument is 18 multiple-choice questions whose options nest by level.

    Within one question the statements form a ladder — "standardised to a *community*
    Standard Dataset Model" (L3) sits above "...to a *locally defined* Dataset Model"
    (L2) — so an option cannot honestly be true while a lower rung of the same
    question is false. Scoring indicators independently can produce exactly that
    incoherence, so the scorer demotes rather than publishing it.
    """

    def test_the_questionnaire_is_carried(self):
        data = _yaml()
        questions = data["questions"]
        assert len(questions) == 18
        assert sum(len(q["options"]) for q in questions) == 73
        assert any(q["multi_select"] for q in questions)

    def test_option_levels_agree_with_the_master_sheet(self):
        """The questionnaire's own LEVEL cell is multi-valued ("Level 1, Level 2"),
        so it cannot order a ladder; the MASTER sheet is authoritative."""
        data = _yaml()
        levels = {i["id"]: i["level"] for i in data["indicators"]}
        for question in data["questions"]:
            for option in question["options"]:
                assert option["level"] == levels[option["id"]], option["id"]

    def test_a_failed_rung_demotes_the_rungs_above_it(self):
        from builder.tools import fair_assessment as fa

        data = {
            "indicators": [
                {"id": "A", "level": 2, "category": "C", "scope": "full", "check": "no"},
                {"id": "B", "level": 3, "category": "C", "scope": "full", "check": "yes"},
            ],
            "questions": [
                {"question": "q", "options": [{"id": "A", "level": 2}, {"id": "B", "level": 3}]}
            ],
        }
        checks = {"no": lambda _s, _g=None: False, "yes": lambda _s, _g=None: True}
        import unittest.mock as m

        with m.patch.dict(fa.DSM_CHECKS, checks):
            verdicts = fa.dsm_verdicts(CrateStateStub(), data, None)
        assert verdicts["A"].value is False
        assert verdicts["B"].value is False, "a higher rung must not stand on a failed one"
        assert "demoted" in verdicts["B"].evidence
        assert "A" in verdicts["B"].evidence, "the evidence must name what blocked it"

    def test_siblings_at_the_same_level_do_not_demote_each_other(self):
        """The ladder runs ACROSS levels. Two options at the same level are
        independent statements, so one failing must not drag the other down."""
        from builder.tools import fair_assessment as fa

        data = {
            "indicators": [
                {"id": "A", "level": 1, "category": "C", "scope": "full", "check": "no"},
                {"id": "B", "level": 1, "category": "C", "scope": "full", "check": "yes"},
            ],
            "questions": [
                {"question": "q", "options": [{"id": "A", "level": 1}, {"id": "B", "level": 1}]}
            ],
        }
        checks = {"no": lambda _s, _g=None: False, "yes": lambda _s, _g=None: True}
        import unittest.mock as m

        with m.patch.dict(fa.DSM_CHECKS, checks):
            verdicts = fa.dsm_verdicts(CrateStateStub(), data, None)
        assert verdicts["B"].value is True

    def test_an_unanswered_rung_neither_blocks_nor_is_blocked(self):
        from builder.tools import fair_assessment as fa

        data = {
            "indicators": [
                {"id": "A", "level": 2, "category": "C", "scope": "full", "check": "none"},
                {"id": "B", "level": 3, "category": "C", "scope": "full", "check": "yes"},
            ],
            "questions": [
                {"question": "q", "options": [{"id": "A", "level": 2}, {"id": "B", "level": 3}]}
            ],
        }
        checks = {"none": lambda _s, _g=None: None, "yes": lambda _s, _g=None: True}
        import unittest.mock as m

        with m.patch.dict(fa.DSM_CHECKS, checks):
            verdicts = fa.dsm_verdicts(CrateStateStub(), data, None)
        assert verdicts["A"].value is None
        assert verdicts["B"].value is True, "absent evidence is not a failed rung"


class TestEveryVerdictCarriesItsEvidence:
    """A bare boolean cannot be audited; the model is a human assessment instrument."""

    def test_graph_checks_report_what_they_measured(self):
        import json

        from builder.tools.fair_assessment import dsm_verdicts

        crate = REPO / "output" / "svhps22_real_input_crate_v20" / "ro-crate-metadata.json"
        if not crate.is_file():
            import pytest

            pytest.skip("no built crate on disk to score")
        graph = json.loads(crate.read_text())["@graph"]
        verdicts = dsm_verdicts(CrateStateStub(), None, graph)
        measured = [v for v in verdicts.values() if v.evidence]
        assert measured, "no verdict carried evidence"
        # Evidence must be a measurement, not a restatement of the verdict.
        joined = " ".join(v.evidence for v in measured)
        assert any(ch.isdigit() for ch in joined), "evidence should quantify what was found"

    def test_verdict_refuses_truthiness(self):
        """Tri-state: `if verdict:` must not silently read None as False."""
        import pytest

        from builder.tools.fair_assessment import Verdict

        with pytest.raises(TypeError, match="tri-state"):
            bool(Verdict(None, ""))


def CrateStateStub():
    from builder.state import CrateState

    return CrateState()
