"""Issue #356: the generic FAIR indicators are DERIVED from the vendored RDA FAIR
Data Maturity Model (``fair/rda_fdmm.xlsx``), not hand-authored.

``fair/indicators.yaml`` is generated by ``scripts/gen_fair_indicators.py`` from the
RDA XLSX (definitions: dimension / priority / text) plus a local scope/check map
(which indicators are assessed intrinsically, and with which check). These tests pin
that contract so the definitions can never silently drift from RDA, while the local
scoring logic — and therefore the scores — stay put.
"""

from __future__ import annotations

import importlib.util
import pathlib

import openpyxl
import yaml

REPO = pathlib.Path(__file__).resolve().parents[1]
INDICATORS_YAML = REPO / "fair" / "indicators.yaml"
RDA_XLSX = REPO / "fair" / "rda_fdmm.xlsx"
GEN = REPO / "scripts" / "gen_fair_indicators.py"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_fair_indicators", GEN)
    mod = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(mod)
    return mod


def _rda_rows() -> dict[str, dict[str, str]]:
    """The canonical RDA indicator definitions, straight from the vendored XLSX."""
    wb = openpyxl.load_workbook(RDA_XLSX, read_only=True, data_only=True)
    ws = wb["FAIR Indicators_v0.05"]
    out: dict[str, dict[str, str]] = {}
    for row in list(ws.iter_rows(values_only=True))[1:]:
        iid = row[4]
        if iid and str(iid).startswith("RDA-"):
            out[str(iid)] = {
                "dimension": str(row[3])[0],  # PRINCIPLE (e.g. "F1") -> "F"
                "priority": str(row[6]).strip().lower(),
                "text": str(row[5]).strip(),
            }
    return out


class TestFairIndicatorsDerivedFromRda:
    def test_indicators_yaml_matches_generator_output(self):
        """The committed indicators.yaml is exactly what the generator emits from the
        RDA XLSX + the local scope map — no hand drift."""
        gen = _load_generator()
        committed = yaml.safe_load(INDICATORS_YAML.read_text())
        assert committed["indicators"] == gen.build_data()["indicators"]

    def test_every_indicator_matches_rda_definition(self):
        """Every indicator id exists in the RDA model, and its dimension / priority /
        text are the RDA values (definitions sourced from RDA, not hand-typed)."""
        rda = _rda_rows()
        committed = yaml.safe_load(INDICATORS_YAML.read_text())
        assert committed["indicators"], "no indicators loaded"
        for ind in committed["indicators"]:
            iid = ind["id"]
            assert iid in rda, f"{iid} is not an RDA FAIR Data Maturity Model indicator"
            assert ind["dimension"] == rda[iid]["dimension"], iid
            assert ind["priority"] == rda[iid]["priority"], iid
            assert ind["text"] == rda[iid]["text"], iid

    def test_fair_scores_unchanged_for_golden_crate(self):
        """Re-sourcing definitions must not move any score (definitions only, not
        logic) — regression against the pre-#356 assessment of S-VHPS21."""
        from builder.tools.fair_assessment import assess_fair_maturity
        from tests.fixtures.vhps_golden_crates import vhps_fixture_state

        rep = assess_fair_maturity(vhps_fixture_state("S-VHPS21"))
        got = {r["id"]: (r.get("passed"), r.get("scope", "")) for r in rep.indicator_results}
        expected = {
            "RDA-F1-02M": (True, ""),
            "RDA-F1-02D": (True, ""),
            "RDA-F1-01M": (False, ""),
            "RDA-F2-01M": (True, ""),
            "RDA-F3-01M": (True, ""),
            "RDA-A1-02M": (None, "out_of_scope"),
            "RDA-A1-04D": (None, "out_of_scope"),
            "RDA-A2-01M": (None, "out_of_scope"),
            "RDA-I1-01M": (True, ""),
            "RDA-I1-02M": (True, ""),
            "RDA-I2-01M": (True, ""),
            "RDA-I3-01M": (True, ""),
            "RDA-I3-03M": (True, ""),
            "RDA-R1-01M": (True, ""),
            "RDA-R1.1-01M": (False, ""),
            "RDA-R1.1-02M": (False, ""),
            "RDA-R1.1-03M": (False, ""),
            "RDA-R1.2-01M": (True, ""),
            "RDA-R1.3-01M": (True, ""),
            "RDA-R1.3-02M": (True, ""),
            "RDA-R1.3-01D": (False, ""),
        }
        assert got == expected
        assert rep.dsm_level == 2
