"""The wire format the data island carries, and what it costs (#694).

`build_explorer_payload` is the readable model: ids everywhere, one dict per
edge. That is what every test and every Python consumer reads, and it stays that
way. What the page *carries* is a compacted encoding of the same thing, because
a mean ``@id`` in a real crate is 53 characters and the model repeats each of
them once per edge endpoint and once per view membership — some 1,800 copies of
strings already sitting in ``nodes``.

The two halves are inverses: :func:`_compact` here and ``expand`` in
``payload_codec.js``, which the browser runs before anything else touches the
payload. Both are tested, and the round trip is tested through the shipped
JavaScript rather than a Python restatement of it.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

from builder.writers.entity_explorer import _compact, build_explorer_payload
from tests.fixtures.crate_graphs import assay_lane_graph, tabbed_views_graph

pytestmark = pytest.mark.timeout(180)

_REPO = Path(__file__).resolve().parents[1]
_CODEC = _REPO / "builder" / "writers" / "payload_codec.js"
_PROBE = _REPO / "tests" / "fixtures" / "codec_probe.js"


def _node_exe() -> str:
    exe = shutil.which("node")
    if exe is None:  # pragma: no cover — depends on the machine, not the code
        pytest.skip("node is not installed; the codec cannot be run")
    return exe


def _expanded(compact: dict) -> dict:
    """Run the SHIPPED expander over *compact* and return what it produced."""
    result = subprocess.run(
        [_node_exe(), str(_PROBE), str(_CODEC)],
        input=json.dumps(compact),
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


class TestTheRoundTripIsLossless:
    """The only property that matters: the browser must see what Python built."""

    @pytest.mark.parametrize("graph", [tabbed_views_graph(), assay_lane_graph()])
    def test_expanding_a_compacted_payload_returns_it_unchanged(self, graph):
        payload = build_explorer_payload(graph)
        assert _expanded(_compact(payload)) == payload

    def test_the_shipped_javascript_is_what_expands_it(self):
        """Not a Python reimplementation: a codec tested against its own mirror
        proves the mirror, not the page."""
        assert _CODEC.exists()

    def test_an_edge_survives_with_its_label(self):
        payload = build_explorer_payload(assay_lane_graph())
        back = _expanded(_compact(payload))
        assert back["edges"] == payload["edges"]

    def test_view_membership_survives(self):
        payload = build_explorer_payload(assay_lane_graph())
        back = _expanded(_compact(payload))
        for before, after in zip(payload["views"], back["views"]):
            assert before["members"] == after["members"], before["key"]

    def test_a_name_that_differs_from_its_label_is_not_dropped(self):
        """The saving comes from omitting ``name`` only where it repeats
        ``label``, so the case where they differ is the one that can lose data.

        Built here rather than taken from a fixture, because none of them carry
        it: a label is badged where the crate marks a file autogenerated, and the
        badge abbreviates a 16-character warning that would otherwise eat the
        whole label. That is exactly when the crate's own wording must survive.
        """
        graph = {
            "@graph": [
                {"@id": "ro-crate-metadata.json", "about": {"@id": "./"}},
                {
                    "@id": "./",
                    "@type": "Dataset",
                    "additionalType": "Investigation",
                    "name": "An investigation",
                    "hasPart": [{"@id": "generated.html"}],
                },
                {
                    "@id": "generated.html",
                    "@type": "File",
                    "name": "AUTOGENERATED — RO-Crate maturity report",
                },
            ]
        }
        payload = build_explorer_payload(graph)
        differing = [n for n in payload["nodes"] if n["name"] != n["label"]]
        assert differing, "the badged-label case is no longer reachable"

        compact = _compact(payload)
        omitted = [n for n in compact["nodes"] if "name" not in n]
        assert omitted, "nothing was saved at all"

        back = {n["id"]: n for n in _expanded(compact)["nodes"]}
        for node in differing:
            assert back[node["id"]]["name"] == node["name"], node["id"]


class TestItActuallySaves:
    def test_the_island_is_materially_smaller(self):
        payload = build_explorer_payload(assay_lane_graph())
        before = len(json.dumps(payload, separators=(",", ":")))
        after = len(json.dumps(_compact(payload), separators=(",", ":")))
        assert after < before * 0.85, f"{before} -> {after}"

    def test_no_edge_carries_an_id_string(self):
        """The point: an endpoint is an index into `nodes`, not a 53-character
        repeat of what `nodes` already holds."""
        compact = _compact(build_explorer_payload(assay_lane_graph()))
        for edge in compact["edges"]:
            assert isinstance(edge[0], int) and isinstance(edge[1], int), edge

    def test_the_glyph_is_no_longer_shipped(self):
        """Nothing has drawn it since #688."""
        compact = _compact(build_explorer_payload(assay_lane_graph()))
        for category in compact["categories"].values():
            assert "glyph" not in category, category


class TestTheModelItselfIsUnchanged:
    """Compaction is a wire format, not a change to what the explorer means."""

    def test_the_payload_still_reads_with_ids(self):
        payload = build_explorer_payload(assay_lane_graph())
        assert all(isinstance(e["src"], str) for e in payload["edges"])
        assert all(isinstance(m, str) for v in payload["views"] for m in v["members"])

    def test_every_node_still_carries_a_name(self):
        payload = build_explorer_payload(assay_lane_graph())
        assert all(n.get("name") for n in payload["nodes"])


class TestThePageLoadsItInTime:
    """The app expands on its first line, so order is a requirement."""

    def _section(self) -> str:
        from builder.writers.entity_explorer import render_explorer_section

        return render_explorer_section(assay_lane_graph())

    def test_the_codec_is_shipped(self):
        assert "root.PayloadCodec = factory" in self._section()

    def test_it_loads_before_the_app_that_calls_it(self):
        section = self._section()
        assert section.index("root.PayloadCodec = factory") < section.index(
            "window.PayloadCodec.expand"
        )

    def test_the_island_is_the_compacted_form(self):
        """Not the model: shipping both would be the whole saving given back."""
        import re

        section = self._section()
        island = re.search(
            r'<script id="ex-data" type="application/json">(.*?)</script>', section, re.S
        )
        assert island, "the data island is gone"
        data = json.loads(island.group(1).replace("\\u003c", "<").replace("\\u003e", ">"))
        assert all(isinstance(e[0], int) for e in data["edges"])

    def test_the_saving_is_real_on_a_crate_sized_payload(self):
        """Stated as a floor rather than a number, so the test measures the
        property and not one crate's arithmetic."""
        from builder.writers.entity_explorer import _data_island

        payload = build_explorer_payload(assay_lane_graph())
        model = len(json.dumps(payload, ensure_ascii=True, separators=(",", ":")))
        wire = len(_data_island(payload))
        assert wire < model * 0.9, f"{model} -> {wire}"
