"""Tool that assembles an RO-Crate directory from CrateState entity data.

The crate is assembled with `ro-crate-py` (the official RO-Crate SDK): a
`ROCrate` is created, the ISA-Tox JSON-LD context is attached, and the entity
graph is built by `builder/tools/_crate_mapping.py` (which maps each CrateState
entity onto its ISA-Tox domain-model class, resolves cross-entity references, and
wires the Investigation → Study → Assay → LabProcess graph). `crate.write()` then
serialises a valid `ro-crate-metadata.json`.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from rocrate.model import File
from rocrate.rocrate import ROCrate

import builder.config as _config
from builder.state import CrateState
from builder.tools._crate_mapping import (
    AUTOGENERATED_MARKER,
    _file_dest,
    populate_crate,
)
from profiles.context import ISA_TOX_CONTEXT

logger = logging.getLogger(__name__)

# The placeholder root name ro-crate-py / _crate_mapping fall back to when the
# session has no title. ro-crate-py's bundled preview renders this verbatim as the
# page header, so an untitled crate shows a meaningless "Untitled Investigation"
# (#272). _apply_root_name replaces it with the Investigation/Study name.
_PLACEHOLDER_ROOT_NAME = "Untitled Investigation"
# The placeholder root description _crate_mapping falls back to when the session
# has neither a description nor a title. Treated as a placeholder so the
# Investigation/Study description (or name) can replace it (#272).
_PLACEHOLDER_ROOT_DESCRIPTION = "RO-Crate generated by vitro-crate."
# Final fallback when neither a session title nor an Investigation/Study name is
# available — still meaningful, never the bare placeholder.
_DEFAULT_ROOT_NAME = "ISA-Tox RO-Crate"


def _first_named(state: CrateState, entity_type: str) -> str | None:
    """The ``name`` of the first entity of *entity_type* with a non-empty name."""
    for entity in state.list_entities(entity_type):
        name = entity.fields.get("name")
        if isinstance(name, str) and name.strip():
            return name.strip()
    return None


def _first_field_value(state: CrateState, entity_type: str, field: str) -> str | None:
    """The first non-empty string *field* across entities of *entity_type*."""
    for entity in state.list_entities(entity_type):
        value = entity.fields.get(field)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


def _apply_root_name(crate: ROCrate, state: CrateState) -> None:
    """Give the crate root (``./``) a meaningful name/description for the preview.

    ro-crate-py's bundled preview template (rendered via ``_SafePreview``, #169)
    uses the Root Data Entity ``name`` as the page header. When the session has no
    title, ``_crate_mapping`` leaves the placeholder ``"Untitled Investigation"``
    there, so the preview reads as untitled (#272). This derives a better name —
    and description — from the crate's own ISA backbone and sets it through the
    ro-crate-py API (``crate.root_dataset``):

    1. Investigation ``name`` (the ISA root is the Investigation),
    2. else the first Study ``name``,
    3. else a sensible default (never the bare placeholder).

    A session-level title (``state.metadata.title``) still wins: it is applied
    earlier in assembly, so the root name is already non-placeholder and is left
    untouched. The derivation is deterministic from state, so the graph hash is
    unaffected.
    """
    current = crate.root_dataset.get("name")
    if isinstance(current, str) and current.strip() and current != _PLACEHOLDER_ROOT_NAME:
        return  # An explicit session title (or folded Investigation name) already set it.

    name = (
        _first_named(state, "Investigation") or _first_named(state, "Study") or _DEFAULT_ROOT_NAME
    )
    crate.root_dataset["name"] = name

    current_desc = crate.root_dataset.get("description")
    # The placeholder description mirrors the (placeholder) name or is the generic
    # default (see _crate_mapping), so refresh it whenever it is empty or still a
    # placeholder rather than a real Investigation/Study description.
    if not (isinstance(current_desc, str) and current_desc.strip()) or current_desc in (
        _PLACEHOLDER_ROOT_NAME,
        _PLACEHOLDER_ROOT_DESCRIPTION,
        current,
    ):
        description = (
            _first_field_value(state, "Investigation", "description")
            or _first_field_value(state, "Study", "description")
            or name
        )
        crate.root_dataset["description"] = description


def _default_crate_path(state: CrateState) -> str:
    """Return a session-derived default crate path.

    The convention is ``sessions/<session_id>/working_crate/``, which matches
    the session persistence layout described in AGENTS.md.
    """
    session_id = state.session_id or "unknown"
    return str(_config.session_root() / session_id / "working_crate")


def assemble_crate(
    state: CrateState,
    output_dir: Path | None = None,
    *,
    materialize_payload: bool = True,
    include_all_scanned: bool = True,
) -> ROCrate:
    """Assemble an in-memory `ROCrate` from CrateState — no disk write.

    This is the shared assembly step behind both :func:`export_crate` (which
    then writes the crate to disk) and ``build_and_validate`` (which generates
    the metadata document and validates it in memory). Splitting it out keeps
    disk writes confined to :func:`export_crate`.

    Args:
        state: The CrateState to build from.
        output_dir: Crate root, used only when payload is materialised. ``None``
            for the pure in-memory path.
        materialize_payload: When False, no payload file is written (see
            :func:`builder.tools._crate_mapping.populate_crate`).
        include_all_scanned: When True (default), every file in
            ``state.scanned_files`` that is not already a drafted ``File`` entity
            is auto-included as a ``File`` leaf, so the crate packages the whole
            dataset (#175). The in-memory ``build_and_validate`` path passes
            False — plain leaves don't change the validation verdict and skipping
            them keeps the ReAct loop fast.

    Returns:
        A populated :class:`ROCrate`. Nothing is written unless the caller
        invokes ``crate.write()``.
    """
    crate = ROCrate()
    crate.metadata.extra_contexts = ISA_TOX_CONTEXT
    populate_crate(
        state,
        crate,
        output_dir,
        materialize_payload=materialize_payload,
        include_all_scanned=include_all_scanned,
    )
    # Give the root (./) a meaningful name/description from the Investigation
    # (fallback Study, then a default) so ro-crate-py's preview header isn't
    # "Untitled Investigation" (#272).
    _apply_root_name(crate, state)
    return crate


_GRAPH_FILENAME = "ro-crate-graph.mmd"


def _add_safe_preview(crate: ROCrate) -> None:
    """Add an XSS-safe ``ro-crate-preview.html`` to *crate* (#169).

    ro-crate-py's bundled :class:`~rocrate.model.preview.Preview` renders its
    HTML through a Jinja2 ``Template`` with autoescaping OFF, so crate-controlled
    strings (the crate ``name``/``description``, every entity ``@id``/``@type``)
    are interpolated raw. A crate whose name is ``<script>…</script>`` therefore
    yields a preview that executes when opened — stored XSS.

    We subclass the bundled ``Preview`` and re-render its *own* vendored template
    through a Jinja2 environment with ``autoescape=True``, so every ``{{ … }}``
    is HTML-escaped (tags become inert text, attribute values can't break out).
    The metadata graph is untouched — escaping is presentation-layer only, so
    ``ro-crate-metadata.json`` keeps the original literal values.
    """
    import os

    from jinja2 import Environment, select_autoescape
    from rocrate.model.preview import Preview

    class _SafePreview(Preview):
        def generate_html(self) -> str:  # type: ignore[override]
            # Locate the vendored template relative to the Preview module so we
            # render exactly what ro-crate-py ships, just with autoescaping on.
            import rocrate.model.preview as _preview_mod

            tpl_dir = os.path.join(
                os.path.dirname(os.path.abspath(_preview_mod.__file__)), "..", "templates"
            )
            with open(os.path.join(tpl_dir, "preview_template.html.j2"), encoding="utf-8") as fh:
                template_source = fh.read()

            env = Environment(autoescape=select_autoescape(default=True, default_for_string=True))

            def stringify(a: Any) -> str:
                if isinstance(a, list):
                    return ", ".join(str(x) for x in a)
                if isinstance(a, str):
                    return a
                jsonld = getattr(a, "_jsonld", None)
                if jsonld and jsonld.get("name"):
                    return str(jsonld["name"])
                return str(a)

            def is_object_list(a: Any) -> bool:
                if isinstance(a, list):
                    return any(not isinstance(obj, str) for obj in a)
                return False

            env.globals["stringify"] = stringify  # ty: ignore[invalid-assignment]
            env.globals["is_object_list"] = is_object_list  # ty: ignore[invalid-assignment]
            src = env.from_string(template_source)

            context_entities = [e._jsonld for e in self.crate.contextual_entities]
            data_entities = [e._jsonld for e in self.crate.data_entities]
            return src.render(crate=self.crate, context=context_entities, data=data_entities)

    crate.add(_SafePreview(crate))


def _embed_crate_graph(crate: ROCrate) -> None:
    """Embed the crate's entity-graph diagram into the crate and register it
    (#130).

    The Mermaid diagram is generated from the crate's current ``@graph`` (before
    its own File node is added, so it never depicts itself) and added as
    ``ro-crate-graph.mmd`` — a ``File`` + ``CreativeWork`` ``about`` the Root Data
    Entity, which ro-crate-py also links from ``./``'s ``hasPart``, so the diagram
    travels with the data and is reachable from the root. The Mermaid text is the
    File's in-memory source, so ``crate.write()`` materialises it (no separate
    disk write, no "missing source" warning).
    """
    from io import StringIO

    from builder.writers.provenance_dag import render_crate_graph

    mermaid = render_crate_graph(crate.metadata.generate())
    crate.add(
        File(
            crate,
            StringIO(mermaid),
            dest_path=_GRAPH_FILENAME,
            properties={
                "@type": ["File", "CreativeWork"],
                "name": f"{AUTOGENERATED_MARKER} — RO-Crate entity graph",
                "description": (
                    "Mermaid node-link diagram of this crate's entities and their "
                    "relationships (three-layer grouping, hasPart, process I/O, "
                    "annotations), generated by vitro-crate."
                ),
                "encodingFormat": "text/vnd.mermaid",
                "about": {"@id": "./"},
            },
        )
    )


def _embed_maturity_report(crate: ROCrate, state: CrateState) -> None:
    """Embed the maturity report into the crate and register it (#85).

    Renders ``ro-crate-metadata-maturity.html`` — profile adherence (computed in-memory
    from the crate's current ``@graph``), FAIR + DSM, OECD MIT coverage, and
    reproducibility readiness — and adds it as a ``File`` + ``CreativeWork``
    ``about`` ``./`` (the HTML is the File's in-memory source, materialised by
    ``crate.write()``). Mirrors :func:`_embed_crate_graph`.
    """
    from io import StringIO

    from builder.writers.maturity_report import REPORT_FILENAME, build_maturity_html

    # Renders from state.validation (no re-validate) so export stays cheap (#85).
    # Pass the crate's current @graph so the report can fold in the provenance
    # chain + graph-topology strip drawn from real serialized entities.
    page = build_maturity_html(state, graph=crate.metadata.generate())
    crate.add(
        File(
            crate,
            StringIO(page),
            dest_path=REPORT_FILENAME,
            properties={
                "@type": ["File", "CreativeWork"],
                "name": f"{AUTOGENERATED_MARKER} — RO-Crate maturity report",
                "description": (
                    "Profile adherence, FAIR/DSM, OECD MIT coverage, and "
                    "reproducibility readiness for this crate, generated by vitro-crate."
                ),
                "encodingFormat": "text/html",
                "about": {"@id": "./"},
            },
        )
    )


def export_crate(
    state: CrateState,
    output_path: str | None = None,
    *,
    embed_graph: bool = True,
    embed_report: bool = True,
    validate: bool = True,
) -> dict[str, Any]:
    """Assemble an RO-Crate from CrateState and write it to disk (ro-crate-py).

    This is the only step that touches disk: it creates the output directory,
    assembles a `ROCrate` from the state, and writes `ro-crate-metadata.json`
    plus any payload. It also embeds the browsable preview
    (`ro-crate-preview.html`, #86) and — unless disabled — the entity-graph
    diagram (`ro-crate-graph.mmd`, a CreativeWork about `./`, #130) so the written
    crate is self-describing and visually explorable. For a fast, zero-disk
    conformance check during the agent loop, use ``build_and_validate`` instead.

    Args:
        state: The current CrateState to build from.
        output_path: Path where the crate directory should be created.
            When omitted, falls back to ``state.metadata.output_path`` (the
            user-configured destination), then to
            ``sessions/<session_id>/working_crate/``.
        embed_graph: Write the entity-graph diagram into the crate (default
            True). Set False to skip the visualization artifact.
        embed_report: Write the maturity report (ro-crate-metadata-maturity.html, #85)
            into the crate (default True). Set False to skip it.
        validate: Validate before writing, unless the recorded verdict is already
            current (default True). The export embeds a maturity report whose
            headline verdict comes from ``state.validation``; without this, a
            crate edited after its last validation ships a report describing a
            state nobody checked. A failing validation does NOT block the write —
            the crate is still written and the report states the real verdict.

    Returns:
        A dict with keys:
            success (bool): Whether the crate was built successfully.
            crate_path (str): The output path used (can be passed directly
                to :func:`validate`).
            error (str | None): Error message if success is False.
            validation (dict): ``{"ran", "reason", "ok", "error"}`` from the
                pre-write freshness check — ``reason`` is ``"fresh"`` (skipped,
                the recorded verdict still describes this crate),
                ``"never-validated"`` or ``"stale"``. Absent when
                ``validate=False``.
    """
    try:
        if not output_path:
            # Honor the user-configured destination (set from the CLI --output /
            # state.metadata.output_path) before falling back to the session dir.
            output_path = state.metadata.output_path or _default_crate_path(state)

        output_dir = Path(output_path)
        output_dir.mkdir(parents=True, exist_ok=True)

        # Validate BEFORE assembling, so the maturity report embedded below
        # reports on the crate actually being written. Skipped when the recorded
        # verdict's fingerprint still matches the state (re-validating an
        # unchanged crate would burn the dominant tox pass for a verdict we
        # already hold). Never blocks the write: the report tells the truth.
        validation_info: dict[str, Any] | None = None
        if validate:
            from builder.tools.validation import ensure_validated

            validation_info = ensure_validated(state)
            if validation_info["error"]:
                logger.warning(
                    "Export-time validation did not complete (%s); the maturity "
                    "report will mark the verdict unverified",
                    validation_info["error"],
                )

        # Wire domain entities that nothing references onto the process that used
        # them (#438/#273). A compound reaches the experiment only through the
        # Exposure's `chemicals` field, and neither build arm guarantees that is
        # set — a real 22-compound crate exported with `chemicals=None` on every
        # process, leaving all 22 orphaned. One Exposure and N unreferenced
        # compounds have exactly one sensible wiring, so it is done rather than
        # asked; genuinely ambiguous cases are refused and reported, not guessed.
        try:
            from builder.tools.composites import wire_unreferenced_domain_entities

            wiring = wire_unreferenced_domain_entities(state)
            if wiring["wired"]:
                logger.info("Wired unreferenced domain entities: %s", wiring["wired"])
            if wiring["ambiguous"]:
                logger.warning("Domain wiring needs a human: %s", wiring["ambiguous"])
        except Exception as wire_err:  # noqa: BLE001 — wiring never fails an export
            logger.warning("Could not wire unreferenced domain entities: %s", wire_err)
            wiring = {"wired": {}, "ambiguous": []}

        # Stamp what produced this crate — application, version, model, and the
        # run's tokens/cost/wall-clock — immediately before assembly, so the
        # figures cover the whole session up to this write (#generator).
        try:
            state.stamp_generator()
        except Exception as gen_err:  # noqa: BLE001 — provenance never fails an export
            logger.warning("Could not record generator provenance: %s", gen_err)

        crate = assemble_crate(state, output_dir, materialize_payload=True)
        # Embed the standard ro-crate-py preview (ro-crate-preview.html, a
        # CreativeWork about ./) so the written crate is browsable without
        # tooling (#86) — rendered through an autoescaping template so
        # crate-controlled strings can't inject script (XSS, #169).
        _add_safe_preview(crate)

        # Embed the entity-graph diagram (ro-crate-graph.mmd, a CreativeWork
        # about ./) so the crate is visually explorable and self-describing
        # (#130). Best-effort: a rendering failure must not fail the export.
        if embed_graph:
            try:
                _embed_crate_graph(crate)
            except Exception as graph_err:  # noqa: BLE001 — never fail export on the viz
                logger.warning("Could not embed crate graph: %s", graph_err)

        # Embed the maturity report (ro-crate-metadata-maturity.html, a CreativeWork about
        # ./, #85). Best-effort: a reporting failure must not fail the export.
        if embed_report:
            try:
                _embed_maturity_report(crate, state)
            except Exception as report_err:  # noqa: BLE001 — never fail export on the report
                logger.warning("Could not embed maturity report: %s", report_err)

        crate.write(str(output_dir))

        # Remember where it landed: without this the state cannot say where the
        # crate went, so the goodbye summary (and a later re-export) had to guess
        # the default even when the caller named a different destination.
        state.metadata.output_path = output_path
        state.metadata.exported_at = _config.now().isoformat()

        logger.info("Crate exported to %s", output_path)
        out: dict[str, Any] = {"success": True, "crate_path": output_path, "error": None}
        if validation_info is not None:
            out["validation"] = validation_info
        # Empty templates written to keep the derivation chain complete (#438).
        # Returned so the caller can ask the user to confirm or replace them —
        # they are the one part of the payload that carries no real data.
        provisional = sorted(
            _file_dest(fe)
            for fe in state.list_entities("File")
            if fe.fields.get("provisional")
        )
        if provisional:
            out["provisional_tables"] = provisional
        if wiring["wired"] or wiring["ambiguous"]:
            out["wiring"] = wiring
        return out

    except OSError as e:
        logger.error("Failed to create crate at %s: %s", output_path, e)
        return {"success": False, "crate_path": output_path, "error": str(e)}
    except Exception as e:
        logger.error("Unexpected error building crate: %s", e)
        return {"success": False, "crate_path": output_path, "error": str(e)}


def build_crate(state: CrateState, output_path: str | None = None) -> dict[str, Any]:
    """Back-compat alias for :func:`export_crate` (the on-disk writer)."""
    return export_crate(state, output_path)


# ---------------------------------------------------------------------------
# Tool registration
# ---------------------------------------------------------------------------
from builder.tools.registry import TOOL_REGISTRY  # noqa: E402

TOOL_REGISTRY.register("export_crate", export_crate, takes_state=True)
TOOL_REGISTRY.register("build_crate", build_crate, takes_state=True)
