"""
IUCLID / OHT 201 controlled-vocabulary resolver.

Resolves a free-text value against an IUCLID phrase group (picklist) and emits
it as a machine-actionable ``schema:DefinedTerm`` carrying the authoritative
IUCLID phrase code (``termCode``) and a link to its phrase group
(``inDefinedTermSet``). This is the ``sampleType -> NCIT`` pattern generalised to
the harmonised-template vocabularies.

The value sets are loaded from the committed catalogue
``profiles/mit-data/oht201_value_sets.json`` (generated by
``tools/mit/build_value_sets.py``).

Note: IUCLID phrase codes are not public PURLs, so the ``@id`` is a stable
profile-namespaced IRI; the authoritative identity is the ``termCode`` (the
IUCLID code) within its ``inDefinedTermSet`` (the phrase group).
"""

from __future__ import annotations

import difflib
import functools
import json
import re
from pathlib import Path

from rocrate.model import ContextEntity
from rocrate.rocrate import ROCrate

_BASE = "https://w3id.org/ro/crate/isa-tox/1.0/iuclid"
_CATALOG = (
    Path(__file__).resolve().parents[1]
    / "profiles"
    / "mit-data"
    / "oht201_value_sets.json"
)
_FUZZY_THRESHOLD = 0.86


@functools.lru_cache(maxsize=1)
def _catalog() -> dict:
    try:
        return json.loads(_CATALOG.read_text(encoding="utf-8"))
    except Exception:
        return {"phrase_groups": {}, "bindings": {}}


def phrase_group_values(phrase_group: str) -> list[dict]:
    """Return the [{code, text, open?}] value set for a phrase group ({} if unknown)."""
    return _catalog().get("phrase_groups", {}).get(phrase_group, [])


def resolve(value: str, phrase_group: str) -> dict | None:
    """Resolve ``value`` to a picklist term for ``phrase_group``.

    Returns a dict ``{"code", "text", "freetext": bool}`` or ``None`` if the
    phrase group is unknown. Matching is: exact (case-insensitive) -> fuzzy
    (>= threshold) -> the group's open ``other:`` term carrying the raw value ->
    an uncoded term carrying the raw value.
    """
    terms = phrase_group_values(phrase_group)
    if not terms:
        return None
    v = (value or "").strip()
    vl = v.lower()

    for t in terms:
        if t.get("text", "").strip().lower() == vl:
            return {"code": t.get("code", ""), "text": t.get("text", v), "freetext": False}

    texts = [t.get("text", "") for t in terms]
    close = difflib.get_close_matches(v, texts, n=1, cutoff=_FUZZY_THRESHOLD)
    if close:
        t = terms[texts.index(close[0])]
        return {"code": t.get("code", ""), "text": t.get("text", v), "freetext": False}

    # No controlled match: use the group's open term if it has one, else uncoded.
    open_t = next((t for t in terms if t.get("open")), None)
    if open_t:
        return {"code": open_t.get("code", ""), "text": v, "freetext": True}
    return {"code": "", "text": v, "freetext": True}


def _slug(text: str) -> str:
    return re.sub(r"[^\w.-]", "_", (text or "")).strip("_").lower() or "value"


def iuclid_termset(crate: ROCrate, phrase_group: str) -> ContextEntity:
    """Get-or-create the DefinedTermSet entity for a phrase group."""
    ts_id = f"{_BASE}/{phrase_group}"
    return crate.add(ContextEntity(crate, ts_id, properties={
        "@type": "DefinedTermSet",
        "name": f"IUCLID phrase group {phrase_group}",
    }))


def iuclid_term(crate: ROCrate, value: str, phrase_group: str):
    """Emit ``value`` as an IUCLID-coded ``schema:DefinedTerm`` and return it.

    Returns ``None`` when the phrase group is unknown (caller should fall back to
    a plain value). The DefinedTermSet for the group is added once and reused.
    """
    m = resolve(value, phrase_group)
    if m is None:
        return None
    termset = iuclid_termset(crate, phrase_group)
    props: dict = {
        "@type": "DefinedTerm",
        "name": m["text"],
        "inDefinedTermSet": termset,
    }
    if m["code"]:
        props["termCode"] = m["code"]
    if m["code"] and not m["freetext"]:
        term_id = f"{_BASE}/{phrase_group}/{m['code']}"
    else:
        # open / uncoded free text: keep the term distinct by its slugged value.
        term_id = f"{_BASE}/{phrase_group}/{_slug(m['text'])}"
    return crate.add(ContextEntity(crate, term_id, properties=props))
