"""Tool specifications for LLM function calling."""

TOOL_SPECS = [
    {"name": "draft_investigation", "description": "Create Investigation entity", "parameters": {"type": "object", "properties": {"hints": {"type": "object"}}, "required": ["hints"]}},
    {"name": "draft_study", "description": "Create Study entity linked to an investigation", "parameters": {"type": "object", "properties": {"investigation_id": {"type": "string"}, "hints": {"type": "object"}}, "required": ["investigation_id", "hints"]}},
    {"name": "draft_assay", "description": "Create Assay entity linked to a study", "parameters": {"type": "object", "properties": {"study_id": {"type": "string"}, "hints": {"type": "object"}}, "required": ["study_id", "hints"]}},
    {"name": "draft_molecular_entity", "description": "Create MolecularEntity from compound name", "parameters": {"type": "object", "properties": {"name": {"type": "string"}, "hints": {"type": "object"}}, "required": ["name", "hints"]}},
    {"name": "draft_cell_line_sample", "description": "Create CellLineSample from cell line name", "parameters": {"type": "object", "properties": {"name": {"type": "string"}, "hints": {"type": "object"}}, "required": ["name", "hints"]}},
    {"name": "draft_process", "description": "Create LabProcess (CellCulture/Exposure/EndpointReadout/DataAnalysis)", "parameters": {"type": "object", "properties": {"assay_id": {"type": "string"}, "process_type": {"type": "string", "enum": ["CellCulture", "Exposure", "EndpointReadout", "DataAnalysis"]}, "hints": {"type": "object"}}, "required": ["assay_id", "process_type", "hints"]}},
    {"name": "draft_person", "description": "Create Person entity", "parameters": {"type": "object", "properties": {"name": {"type": "string"}, "hints": {"type": "object"}}, "required": ["name", "hints"]}},
    {"name": "draft_organization", "description": "Create Organization entity", "parameters": {"type": "object", "properties": {"name": {"type": "string"}, "hints": {"type": "object"}}, "required": ["name", "hints"]}},
    {"name": "draft_publication", "description": "Create Publication entity from DOI", "parameters": {"type": "object", "properties": {"doi": {"type": "string"}, "hints": {"type": "object"}}, "required": ["doi", "hints"]}},
    {"name": "update_entity", "description": "Update fields on an entity", "parameters": {"type": "object", "properties": {"entity_id": {"type": "string"}, "patch": {"type": "object"}}, "required": ["entity_id", "patch"]}},
    {"name": "remove_entity", "description": "Remove an entity by id", "parameters": {"type": "object", "properties": {"entity_id": {"type": "string"}}, "required": ["entity_id"]}},
    {"name": "list_entities", "description": "List entities, optionally filtered by type", "parameters": {"type": "object", "properties": {"entity_type": {"type": "string"}}}},
    {"name": "lookup_compound", "description": "Look up chemical compound via PubChem", "parameters": {"type": "object", "properties": {"name": {"type": "string"}}, "required": ["name"]}},
    {"name": "lookup_cell_line", "description": "Look up cell line via Cellosaurus", "parameters": {"type": "object", "properties": {"accession": {"type": "string"}}, "required": ["accession"]}},
    {"name": "lookup_aop", "description": "Look up AOP via AOP-Wiki", "parameters": {"type": "object", "properties": {"aop_id": {"type": "string"}}, "required": ["aop_id"]}},
    {"name": "lookup_bao_term", "description": "Search BAO ontology via OLS", "parameters": {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}},
    {"name": "lookup_orcid", "description": "Look up person via ORCID", "parameters": {"type": "object", "properties": {"orcid_id": {"type": "string"}}, "required": ["orcid_id"]}},
    {"name": "lookup_ror", "description": "Search organization via ROR", "parameters": {"type": "object", "properties": {"name": {"type": "string"}}, "required": ["name"]}},
    {"name": "lookup_doi", "description": "Look up publication via Crossref", "parameters": {"type": "object", "properties": {"doi": {"type": "string"}}, "required": ["doi"]}},
    {"name": "verify_identifier", "description": "Check identifier resolves at source", "parameters": {"type": "object", "properties": {"entity_id": {"type": "string"}, "field": {"type": "string"}}, "required": ["entity_id", "field"]}},
    {"name": "build_crate", "description": "Build RO-Crate from state", "parameters": {"type": "object", "properties": {"output_path": {"type": "string"}}, "required": ["output_path"]}},
    {"name": "validate", "description": "Run three-pass SHACL validation", "parameters": {"type": "object", "properties": {"crate_path": {"type": "string"}}, "required": ["crate_path"]}},
    {"name": "assess_mit_coverage", "description": "Score MIT coverage from entity fields", "parameters": {"type": "object", "properties": {}}},
    {"name": "assess_fair_maturity", "description": "Score FAIR maturity from metadata", "parameters": {"type": "object", "properties": {}}},
    {"name": "save_session", "description": "Save session to disk", "parameters": {"type": "object", "properties": {"label": {"type": "string"}}}},
    {"name": "get_status", "description": "Get current session status", "parameters": {"type": "object", "properties": {}}},
    {"name": "scan_files", "description": "Scan a directory or zip archive for files. Archives are auto-extracted to a temp dir and scanned transparently. Results are stored in the session state.", "parameters": {"type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]}},
    {"name": "unzip_file", "description": "Extract a zip archive to a directory. Returns the extraction path.", "parameters": {"type": "object", "properties": {"path": {"type": "string"}, "output_dir": {"type": "string"}}, "required": ["path"]}},
    {"name": "verify_all_identifiers", "description": "Verify all filled identifiers in state", "parameters": {"type": "object", "properties": {}}},
]

__all__ = ["TOOL_SPECS"]
