"""RO-Crate maturity report (``ro-crate-metadata-maturity.html``), embedded in the crate (#85).

Renders a self-contained, light-mode evaluation dashboard (inline CSS, no external
assets) covering the four axes from the issue:

* **Profile adherence** — base / ISA / ISA-Tox conformance, reported across the
  three SHACL severity tiers Required / Recommended / Optional (#306), with the
  findings from every assessed tier surfaced as actionable suggestions — an author
  who can see what is merely recommended is far likelier to add it than one told
  only that the crate clears the required bar;
* **FAIR** — the RDA-style indicators rolled up into F/A/I/R pillars plus the Data
  Stewardship Maturity (DSM) level;
* **OECD MIT coverage** — per-module coverage of the in-vitro tox MIT checklist;
* **Reproducibility readiness** — a derived checklist.

``export_crate`` embeds the rendered page as a ``CreativeWork`` ``about`` ``./``,
mirroring the entity-graph (#130) and preview (#86) artifacts.

``build_maturity_html`` is pure and cheap: FAIR/MIT come from the deterministic
assessors and the profile-adherence section is rendered from the crate's existing
``state.validation`` — it does **not** run the SHACL validator. That keeps the
embed in ``export_crate`` free of validation cost; validation is a separate step.
The one caveat is MIT: scoring the checklist requires the assembled ``@graph``,
so a caller that omits ``graph`` makes ``assess_mit_coverage`` assemble one
in-memory (no disk, no network, no SHACL — cheaper than validation by an order of
magnitude, and the export path pays nothing because it already passes its graph).
The alternative was a second scorer that returned 0.0 for every real crate, which
is not cheapness but a wrong answer (#311).

Severity-tier nuance (#306): the fast in-loop path (``build_and_validate``) gates
at REQUIRED severity and never populates ``should_issues`` / ``may_issues``, so an
empty list at those tiers means the tier was *never evaluated*, not that it is
clean. The report models an explicit "not assessed" state for such tiers and never
renders an unevaluated tier as a green zero. Export closes that gap for the written
crate: ``export_crate`` validates at the OPTIONAL gate, which assesses all three
tiers, so a report embedded on the export path normally has a real verdict in every
row — the "not assessed" state remains for reports rendered from a partial verdict.
"""

from __future__ import annotations

import html
from functools import lru_cache
from pathlib import Path
from typing import Any

from builder.state import CrateState, FAIRReport, MITReport, ValidationReport
from builder.tools.fair_assessment import assess_fair_maturity
from builder.tools.mit_assessment import (
    MIT_STANDARD_LABELS,
    assess_mit_coverage,
    mit_was_assessed,
)
from builder.writers.provenance_dag import AUTOGENERATED_BADGE

REPORT_FILENAME = "ro-crate-metadata-maturity.html"

# FAIR dimension letters (as emitted by fair/indicators.yaml) → display names.
_DIM_NAMES = {"F": "Findable", "A": "Accessible", "I": "Interoperable", "R": "Reusable"}


def _validation_has_signal(validation: ValidationReport) -> bool:
    """True if a validation has actually run (some pass set, or any issue logged).

    A default :class:`ValidationReport` (all passes ``False``, no issues) means
    the crate hasn't been validated yet — distinct from "validated and failing".
    """
    return bool(
        validation.base_passed
        or validation.isa_passed
        or validation.tox_passed
        or validation.required_issues
        or validation.should_issues
        or validation.may_issues
        or validation.assessed_tiers
    )


def _reproducibility_checks(state: CrateState) -> list[tuple[str, bool, str]]:
    """Derive a reproducibility-readiness checklist ``(label, ok, hint)``."""
    processes = state.list_entities("LabProcess")
    protocols = state.list_entities("LabProtocol")

    def _has(entity_list: list, keys: tuple[str, ...]) -> bool:
        return any(any(e.fields.get(k) for k in keys) for e in entity_list)

    protocol_ok = bool(protocols) or _has(processes, ("description",))
    io_ok = _has(processes, ("object", "result", "input", "output", "samples", "derives_from"))
    instrument_ok = _has(
        processes,
        ("detection_instrument", "instrument_manufacturer", "software", "data_processing"),
    )
    # A provisional placeholder now materialises as a real (header-only) file so
    # the crate stops claiming files it does not contain (#438) — but it holds no
    # measurements, so counting it here would turn "data files included" green for
    # a crate whose data is still entirely absent.
    data_ok = any(not f.fields.get("provisional") for f in state.list_entities("File"))
    investigations = state.list_entities("Investigation")
    attribution_ok = (
        bool(state.metadata.title)
        and bool(state.list_entities("Person"))
        and (bool(state.metadata.accession) or _has(investigations, ("identifier",)))
    )

    return [
        (
            "Experimental protocol documented",
            protocol_ok,
            "Add a LabProtocol or describe each LabProcess.",
        ),
        (
            "Process inputs/outputs wired",
            io_ok,
            "Link process object/result (the derivation chain) so steps are traceable.",
        ),
        (
            "Instruments / software recorded",
            instrument_ok,
            "Record the detection instrument, manufacturer, or analysis software.",
        ),
        (
            "Data files included",
            data_ok,
            "Attach the raw/processed data files referenced by the assays — the "
            "synthesized placeholder tables are empty templates, not data.",
        ),
        (
            "Attribution & identity",
            attribution_ok,
            "Set a title, at least one Person (author), and an accession/identifier.",
        ),
    ]


# --- severity tiers (#306) -------------------------------------------------
def _plural_issues(n: int) -> str:
    return f"{n} issue" if n == 1 else f"{n} issues"


def _severity_tiers(val: ValidationReport) -> list[dict[str, str]]:
    """Profile-adherence severity tiers rendered from existing validation (#306).

    Returns one dict per tier: ``{tier, state, summary, note}`` where ``state`` is
    ``"ok"`` | ``"no"`` | ``"na"``.

    REQUIRED is the build gate, so it is assessed whenever validation has run; it
    passes only when all three profiles pass with no REQUIRED issues. The SHOULD
    and MAY tiers are populated only by a full validation sweep — the fast in-loop
    path stops at REQUIRED and leaves them empty. An empty SHOULD/MAY tier is
    therefore reported as "not assessed" (``"na"``), never as a green zero: doing
    otherwise would be a false pass for a tier that was never evaluated.

    Called only when :func:`_validation_has_signal` is True (otherwise the whole
    section renders the "not yet validated" branch).
    """
    n_pass = sum((val.base_passed, val.isa_passed, val.tox_passed))
    req_ok = n_pass == 3 and not val.required_issues
    tiers: list[dict[str, str]] = [
        {
            "tier": "Required",
            "state": "ok" if req_ok else "no",
            "summary": f"{n_pass} / 3 profiles",
            "note": "Blocking — every layer must pass to build.",
        }
    ]
    for label, issues, note in (
        ("Recommended", val.should_issues, "SHOULD-level quality checks."),
        ("Optional", val.may_issues, "MAY-level informational checks."),
    ):
        if issues:
            tiers.append(
                {"tier": label, "state": "no", "summary": _plural_issues(len(issues)), "note": note}
            )
        elif label.casefold() in val.assessed_tiers:
            tiers.append(
                {"tier": label, "state": "ok", "summary": "0 issues", "note": note}
            )
        else:
            tiers.append(
                {
                    "tier": label,
                    "state": "na",
                    "summary": "not assessed",
                    "note": "Not evaluated — the build gates at Required.",
                }
            )
    return tiers


def _fair_pillars(fair: FAIRReport) -> list[dict[str, Any]]:
    """Roll the flat FAIR indicator list up into F/A/I/R pillars.

    Each pillar: ``{letter, name, met, total, na, state}`` where ``total`` counts
    only *assessable* indicators (``passed is not None``); indicators marked
    out-of-scope (``passed is None``, e.g. the hosting-level Accessible checks)
    count toward ``na`` and, when a pillar is entirely out of scope, render as
    "n/a" rather than a misleading 0.
    """
    pillars: list[dict[str, Any]] = []
    for letter, name in _DIM_NAMES.items():
        inds = [i for i in fair.indicator_results if str(i.get("dimension") or "") == letter]
        met = sum(1 for i in inds if i.get("passed") is True)
        na = sum(1 for i in inds if i.get("passed") is None)
        total = sum(1 for i in inds if i.get("passed") is not None)
        if total == 0:
            state = "na"
        elif met == total:
            state = "ok"
        elif met == 0:
            state = "low"
        else:
            state = "warn"
        pillars.append(
            {"letter": letter, "name": name, "met": met, "total": total, "na": na, "state": state}
        )
    return pillars


# --- rendering helpers -----------------------------------------------------
_GLYPH = {"ok": "✓", "no": "✗", "na": "–"}
_MK_LABEL = {"ok": "met", "no": "not met", "na": "not assessed"}


def _mk(kind: str) -> str:
    """A status mark (glyph + accessible label) — colour is never the only cue."""
    return f'<span class="mk {kind}" aria-label="{_MK_LABEL[kind]}">{_GLYPH[kind]}</span>'


def _kind(ok: bool | None) -> str:
    if ok is None:
        return "na"
    return "ok" if ok else "no"


def _fill_class(met: int, total: int) -> str:
    if total <= 0:
        return "fill-warn"
    if met >= total:
        return "fill-good"
    if met == 0:
        return "fill-low"
    return "fill-warn"


_ASSET_DIR = Path(__file__).resolve().parent
_CSS_PATH = _ASSET_DIR / "maturity_report.css"
_SHELL_PATH = _ASSET_DIR / "maturity_report.html"


@lru_cache(maxsize=1)
def _load_css() -> str:
    """The report stylesheet, inlined into the self-contained page.

    Kept in a sibling ``maturity_report.css`` so the styling lives apart from the
    Python that assembles the markup; it is embedded (not linked) so the exported
    ``ro-crate-metadata-maturity.html`` renders offline with no external assets.
    """
    return _CSS_PATH.read_text(encoding="utf-8").strip("\n")


@lru_cache(maxsize=1)
def _load_shell() -> str:
    """The document shell (``maturity_report.html``) whose ``__STYLE__`` /
    ``__TITLE__`` / ``__BODY__`` placeholders are filled at render time."""
    return _SHELL_PATH.read_text(encoding="utf-8")


def _render_header(
    title: str,
    accession: str,
    tiers: list[dict[str, str]] | None,
    *,
    stale: bool = False,
) -> str:
    esc = html.escape
    chip = f'<span class="chip mono">{esc(accession)}</span>' if accession else ""
    if tiers is None:
        verdict = (
            '<span class="vpill warning"><span class="glyph"></span>Not yet validated</span>'
            '<span class="vsub">Run validation to populate profile adherence.</span>'
        )
    elif stale:
        # A verdict recorded against a DIFFERENT state. Reporting the old pass
        # would ship a green "Conformant" for a crate nobody checked — strictly
        # worse than admitting the gap, because it looks verified.
        verdict = (
            '<span class="vpill warning"><span class="glyph"></span>Validation out of date</span>'
            '<span class="vsub">The crate changed after this verdict was recorded — '
            "re-validate before trusting it.</span>"
        )
    elif tiers[0]["state"] == "ok":
        verdict = (
            '<span class="vpill good"><span class="glyph"></span>Conformant</span>'
            '<span class="vsub">All required profile layers pass.</span>'
        )
    else:
        verdict = (
            '<span class="vpill critical"><span class="glyph"></span>Not conformant</span>'
            '<span class="vsub">One or more required profile layers fail.</span>'
        )
    return (
        "<header>\n"
        '  <div class="h-left">\n'
        '    <div class="kicker">'
        f'<span class="eyebrow">RO-Crate maturity report</span>{chip}</div>\n'
        f"    <h1>{esc(title)}</h1>\n"
        "  </div>\n"
        f'  <div class="verdict">{verdict}</div>\n'
        "</header>\n"
    )


def _render_kpis(
    tiers: list[dict[str, str]] | None,
    fair: FAIRReport,
    mit: MITReport,
    repro_ready: int,
    repro_total: int,
    chem: dict[str, Any] | None = None,
) -> str:
    # Profile-adherence tile: severity mini-rows, or an "awaiting validation" row.
    if tiers is None:
        prof_mk = _mk("na")
        sev_rows = (
            '<div class="sev-row">'
            + _mk("na")
            + '<span class="sev-t">Awaiting validation</span></div>'
        )
    else:
        prof_mk = _mk(tiers[0]["state"])
        sev_rows = "".join(
            f'<div class="sev-row">{_mk(t["state"])}'
            f'<span class="sev-t">{t["tier"]}</span>'
            f'<span class="sev-s">{t["summary"]}</span></div>'
            for t in tiers
        )
    prof_tile = (
        '<article class="kpi">'
        f'<div class="kpi-h"><span class="eyebrow">Profile adherence</span>{prof_mk}</div>'
        f'<div class="sev">{sev_rows}</div>'
        "</article>"
    )

    # FAIR / DSM tile.
    met_all = sum(1 for i in fair.indicator_results if i.get("passed") is True)
    na_all = sum(1 for i in fair.indicator_results if i.get("passed") is None)
    assessed = sum(1 for i in fair.indicator_results if i.get("passed") is not None)
    fair_sub = f"{met_all} of {assessed} indicators met"
    if na_all:
        fair_sub += f" · {na_all} n/a"
    rungs = "".join(
        f'<span class="rung {"on" if lvl <= fair.dsm_level else "off"}"></span>'
        for lvl in range(1, 6)
    )
    fair_tile = (
        '<article class="kpi">'
        '<div class="kpi-h"><span class="eyebrow">FAIR maturity</span></div>'
        f'<div class="kpi-v"><b>{fair.dsm_level}</b><span class="den">/ 5</span> '
        '<span class="tag-inline">DSM level</span></div>'
        f'<div class="kpi-sub">{fair_sub}</div>'
        f'<div class="ladder" role="img" aria-label="DSM level {fair.dsm_level} of 5">{rungs}</div>'
        "</article>"
    )

    # OECD MIT coverage tile. An MITReport with no module scores is a coverage
    # measurement that never happened (checklist unreadable, or the crate would
    # not assemble) — not a crate that covers nothing. Its 0.0 must not become
    # "0%": that reads identically to a genuinely empty crate, and the aria-label
    # would say "MIT coverage 0%" out loud (#311). Same "not assessed" state the
    # profile tile shows for an unevaluated severity tier (#446).
    if not mit_was_assessed(mit):
        mit_tile = (
            '<article class="kpi">'
            f'<div class="kpi-h"><span class="eyebrow">OECD MIT coverage</span>{_mk("na")}</div>'
            '<div class="kpi-v"><b>–</b></div>'
            '<div class="kpi-sub">not assessed</div>'
            "</article>"
        )
    else:
        completed_all = sum(sc.get("completed", 0) for sc in mit.module_scores.values())
        total_all = sum(sc.get("total", 0) for sc in mit.module_scores.values())
        pct = round(mit.overall_score * 100)
        mit_tile = (
            '<article class="kpi">'
            '<div class="kpi-h"><span class="eyebrow">OECD MIT coverage</span></div>'
            f'<div class="kpi-v"><b>{pct}</b><span class="den">%</span></div>'
            f'<div class="kpi-sub">{completed_all} of {total_all} checklist fields</div>'
            f'<div class="meter" role="img" aria-label="MIT coverage {pct}%">'
            f'<i class="fill-cov" style="width:{pct}%"></i></div>'
            "</article>"
        )

    # Reproducibility tile.
    dots = "".join(
        f'<span class="dot {"on" if i < repro_ready else "off"}"></span>'
        for i in range(repro_total)
    )
    repro_tile = (
        '<article class="kpi">'
        '<div class="kpi-h"><span class="eyebrow">Reproducibility</span></div>'
        f'<div class="kpi-v"><b>{repro_ready}</b><span class="den">/ {repro_total}</span></div>'
        '<div class="kpi-sub">readiness checks met</div>'
        f'<div class="dots" role="img" aria-label="{repro_ready} of {repro_total}">{dots}</div>'
        "</article>"
    )

    # Chemicals tile — only when the crate actually declares compounds, so a
    # non-chemical crate isn't given a tile reading "0".
    chem_tile = ""
    if chem:
        c = chem["counts"]
        wired, total = c["wired"], c["total"]
        id_pct = round(c["fields_met"] / c["fields_total"] * 100) if c["fields_total"] else 0
        chem_tile = (
            '<article class="kpi">'
            '<div class="kpi-h"><span class="eyebrow">Chemicals</span>'
            f'{_mk("ok" if wired == total else "no")}</div>'
            f'<div class="kpi-v"><b>{wired}</b><span class="den">/ {total}</span> '
            '<span class="tag-inline">wired</span></div>'
            f'<div class="kpi-sub">{id_pct}% of identification fields filled</div>'
            f'<div class="meter" role="img" aria-label="identification {id_pct}%">'
            f'<i class="{_fill_class(c["fields_met"], c["fields_total"])}" '
            f'style="width:{id_pct}%"></i></div>'
            "</article>"
        )

    return f'<div class="kpis">{prof_tile}{fair_tile}{mit_tile}{chem_tile}{repro_tile}</div>\n'


# How many findings of each tier the suggestion list shows before it summarises
# the rest. REQUIRED is uncapped: those block conformance, so every one is named.
_SUGGESTION_CAPS: dict[str, int | None] = {
    "required": None,
    "recommended": 10,
    "optional": 5,
}


def _suggestion_items(val: ValidationReport) -> list[str]:
    """Render the improvement list: what to fix, across every assessed tier.

    The export assesses all three tiers, so the report shows all three. Naming a
    RECOMMENDED or OPTIONAL finding is the point of assessing it — a crate whose
    author can see the twelve things that would make it better is more likely to
    get them than one told only that it clears the bar. REQUIRED findings stay
    first and uncapped; the advisory tiers are capped, and a cap that bites says
    how many it hid rather than trailing off silently.
    """
    esc = html.escape
    tiers: list[tuple[str, list[str], str]] = [
        ("required", val.required_issues, '<li class="must"><strong>Must fix:</strong> {msg}</li>'),
        ("recommended", val.should_issues, "<li>Recommended: {msg}</li>"),
        ("optional", val.may_issues, '<li class="opt">Optional: {msg}</li>'),
    ]
    items: list[str] = []
    for tier, issues, template in tiers:
        if not issues:
            continue
        cap = _SUGGESTION_CAPS[tier]
        shown = issues if cap is None else issues[:cap]
        items.extend(template.format(msg=esc(msg)) for msg in shown)
        hidden = len(issues) - len(shown)
        if hidden:
            items.append(
                f'<li class="more">+{hidden} further {tier} '
                f"{'finding' if hidden == 1 else 'findings'} not listed here</li>"
            )
    return items


def _clean_note(val: ValidationReport) -> str:
    """The empty-state line, honest about how much was actually checked."""
    assessed = val.assessed_tiers
    if {"required", "recommended", "optional"} <= assessed:
        return "Clean at every severity tier — nothing outstanding to improve."
    unassessed = [t for t in ("recommended", "optional") if t not in assessed]
    if unassessed:
        return (
            "No outstanding REQUIRED issues. "
            f"The {' and '.join(unassessed).upper()} tier"
            f"{'s were' if len(unassessed) > 1 else ' was'} not assessed."
        )
    return "No outstanding REQUIRED issues."


def _render_profile_section(
    val: ValidationReport, tiers: list[dict[str, str]] | None, *, stale: bool = False
) -> str:
    esc = html.escape
    if stale:
        return (
            "<section>\n"
            '  <div class="sec-h"><h2>Profile adherence</h2>'
            '<span class="sec-meta">out of date</span></div>\n'
            '  <p class="lead">The last recorded verdict was computed against an earlier '
            "version of this crate, so it is not reported here. Re-run validation to "
            "restore profile adherence.</p>\n"
            "</section>\n"
        )
    if tiers is None:
        return (
            "<section>\n"
            '  <div class="sec-h"><h2>Profile adherence</h2></div>\n'
            '  <p class="lead">Not yet validated — run validation to populate profile '
            "adherence.</p>\n"
            "</section>\n"
        )

    profiles = [
        ("RO-Crate 1.2", val.base_passed),
        ("ISA", val.isa_passed),
        ("ISA-Tox", val.tox_passed),
    ]
    cards = "".join(
        f'<div class="prof-card">{_mk(_kind(passed))}<span>{esc(name)}</span>'
        "<em>REQUIRED</em></div>"
        for name, passed in profiles
    )
    detail_rows = "".join(
        f'<div class="sev-drow">{_mk(t["state"])}<span class="st">{t["tier"]}</span>'
        f'<span class="sc">{t["summary"]}</span><span class="sn">{t["note"]}</span></div>'
        for t in tiers
    )
    sugg_items = _suggestion_items(val)
    if sugg_items:
        sugg = f'<ul class="sugg">{"".join(sugg_items)}</ul>'
    else:
        sugg = f'<p class="good-note">{_clean_note(val)}</p>'

    return (
        "<section>\n"
        '  <div class="sec-h"><h2>Profile adherence</h2>'
        '<span class="sec-meta">3 layers · 3 severity tiers</span></div>\n'
        f'  <div class="prof-grid">{cards}</div>\n'
        '  <div class="sev-detail"><span class="sev-detail-label">By severity</span>'
        f"{detail_rows}</div>\n"
        f"  {sugg}\n"
        "</section>\n"
    )


def _render_fair_section(fair: FAIRReport) -> str:
    esc = html.escape
    pillars = _fair_pillars(fair)
    pillar_html = []
    for p in pillars:
        if p["state"] == "na":
            pv = '<span class="pv na">n/a</span>'
            meter = '<div class="meter na" role="img" aria-label="not assessed">out of scope</div>'
            note = "assessed by the hosting repository, not the crate"
        else:
            pct = round(p["met"] / p["total"] * 100) if p["total"] else 0
            fill = _fill_class(p["met"], p["total"])
            pv = f'<span class="pv">{p["met"]}<span class="den">/ {p["total"]}</span></span>'
            meter = (
                f'<div class="meter" role="img" aria-label="{p["met"]} of {p["total"]}">'
                f'<i class="{fill}" style="width:{pct}%"></i></div>'
            )
            note = f"{p['met']} of {p['total']} indicators met"
        pillar_html.append(
            '<div class="pillar">'
            f'<div class="pl-h"><span class="pl-letter">{p["letter"]}</span>'
            f'<span class="pl-name">{esc(p["name"])}</span>{pv}</div>'
            f"{meter}"
            f'<div class="pl-note">{note}</div>'
            "</div>"
        )

    # Disclosure lists for dimensions that have at least one failing indicator.
    discs = []
    for p in pillars:
        inds = [
            i
            for i in fair.indicator_results
            if str(i.get("dimension") or "") == p["letter"] and i.get("passed") is not None
        ]
        if not any(i.get("passed") is False for i in inds):
            continue
        items = "".join(
            f"<li>{_mk(_kind(bool(i.get('passed'))))} "
            f"<span>{esc(str(i.get('text') or i.get('id') or ''))}</span></li>"
            for i in inds
        )
        discs.append(
            f'<details class="disc"><summary>{esc(p["name"])} — {p["met"]} of {p["total"]} '
            f'indicators · what’s missing</summary><ul class="ind">{items}</ul></details>'
        )

    return (
        "<section>\n"
        '  <div class="sec-h"><h2>FAIR</h2>'
        f'<span class="sec-meta">Data Stewardship Maturity <b>{fair.dsm_level}/5</b></span></div>\n'
        f'  <div class="pillars">{"".join(pillar_html)}</div>\n'
        f"  {''.join(discs)}\n"
        "</section>\n"
    )


def _render_mit_section(mit: MITReport) -> str:
    esc = html.escape
    # Nothing measured -> say so, and print no fraction and no percentage. The
    # old empty-scores branch still rendered "0/0 fields · 0%" in the section
    # header, which asserts a coverage figure just as loudly as the bar chart
    # underneath it would have (#311).
    if not mit_was_assessed(mit):
        return (
            "<section>\n"
            '  <div class="sec-h"><h2>OECD MIT coverage</h2>'
            f'<span class="sec-meta">{_mk("na")} not assessed</span></div>\n'
            '  <p class="lead">Coverage of the OECD in-vitro toxicology checklist was not '
            "measured for this crate — the checklist could not be read, or the crate could "
            "not be assembled to score against. This is not a score of zero.</p>\n"
            "</section>\n"
        )
    completed_all = sum(sc.get("completed", 0) for sc in mit.module_scores.values())
    total_all = sum(sc.get("total", 0) for sc in mit.module_scores.values())
    pct = round(mit.overall_score * 100)

    def row(name: str, sc: dict[str, int]) -> str:
        return (
            f'<div class="mrow"><div class="mname">{esc(name)}</div>'
            f'<div class="mbar"><div class="meter" role="img" '
            f'aria-label="{sc.get("completed", 0)} of {sc.get("total", 0)}">'
            f'<i class="fill-cov" style="width:'
            f'{round(sc.get("completed", 0) / sc["total"] * 100) if sc.get("total") else 0}%">'
            "</i></div></div>"
            f'<div class="mfrac">{sc.get("completed", 0)}'
            f'<span class="den">/{sc.get("total", 0)}</span></div>'
            "</div>"
        )

    # Reached only when there ARE module scores — `mit_was_assessed` is exactly
    # "has module scores", so the old empty-scores fallback row is unreachable.
    rows = "".join(row(name, sc) for name, sc in sorted(mit.module_scores.items()))
    body = f'<div class="mit">{rows}</div>'
    if mit.standard_scores:
        # Canonical order first (the YAML's own column order), then any key the
        # label map doesn't know — rendered raw rather than dropped.
        ordered = [k for k in MIT_STANDARD_LABELS if k in mit.standard_scores]
        ordered += sorted(k for k in mit.standard_scores if k not in MIT_STANDARD_LABELS)
        srows = "".join(
            row(MIT_STANDARD_LABELS.get(k, k), mit.standard_scores[k]) for k in ordered
        )
        body += (
            '\n  <h3 class="mit-sub">Per guidance document</h3>\n'
            '  <p class="lead">One parameter can be required by several documents — '
            "rows overlap and do not sum to the checklist total.</p>\n"
            f'  <div class="mit">{srows}</div>'
        )
    return (
        "<section>\n"
        '  <div class="sec-h"><h2>OECD MIT coverage</h2>'
        f'<span class="sec-meta"><b>{completed_all}/{total_all}</b> fields · {pct}%</span></div>\n'
        '  <p class="lead">Coverage of the OECD in-vitro toxicology reporting checklist. Low '
        "coverage is expected for an auto-built crate — it measures how many domain fields are "
        "filled, not whether the crate is valid.</p>\n"
        f"  {body}\n"
        "</section>\n"
    )


def _render_repro_section(checks: list[tuple[str, bool, str]]) -> str:
    esc = html.escape
    ready = sum(1 for _, ok, _ in checks if ok)
    items = "".join(
        f'<li>{_mk(_kind(ok))}<div><span class="rl">{esc(label)}</span>'
        + ("" if ok else f'<span class="hint">{esc(hint)}</span>')
        + "</div></li>"
        for label, ok, hint in checks
    )
    return (
        "<section>\n"
        '  <div class="sec-h"><h2>Reproducibility readiness</h2>'
        f'<span class="sec-meta"><b>{ready}/{len(checks)}</b> met</span></div>\n'
        f'  <ul class="repro">{items}</ul>\n'
        "</section>\n"
    )


# Cap the actionable orphan/dangling lists so a pathological crate can't blow up
# the page; anything beyond is summarised as "+N more" (#310).
_TOPO_LIST_CAP = 10


def _render_topology_detail(nodes: list[dict[str, Any]]) -> str:
    """Make the topology strip's orphan/dangling counts actionable (#310).

    A count alone ("2 orphans") isn't fixable — the reader can't see *which*
    entities are disconnected. This renders a bounded ``<details>`` naming the
    orphaned entities (id + label + type) and the dangling reference targets, read
    straight from the deterministic :func:`build_crate_graph` node model (each node
    carries an ``orphan`` flag and a ``dangling`` status). Pure/cheap — no
    re-validation, no new graph analysis. Returns ``""`` for a clean crate so
    nothing empty is rendered.
    """
    esc = html.escape
    orphans = [n for n in nodes if n.get("orphan")]
    dangling = [n for n in nodes if n.get("status") == "dangling"]
    if not orphans and not dangling:
        return ""

    def _rows(items: list[dict[str, Any]], *, with_type: bool) -> str:
        # Node labels are pre-escaped by build_crate_graph; ids/types are raw.
        rows = []
        for n in items[:_TOPO_LIST_CAP]:
            ty = str(n.get("type") or "")
            tail = f' <span class="ty">{esc(ty)}</span>' if with_type and ty else ""
            rows.append(
                f"<li>{_mk('no')} <code>{esc(str(n['id']))}</code>"
                f"<span>{n.get('label') or ''}{tail}</span></li>"
            )
        extra = len(items) - _TOPO_LIST_CAP
        if extra > 0:
            rows.append(f'<li class="more">+{extra} more</li>')
        return "".join(rows)

    groups = []
    if orphans:
        groups.append(
            '<p class="topo-detail-h">Orphaned entities — not reachable from the '
            "crate root; link each via <code>hasPart</code>, <code>result</code>, "
            f'or <code>about</code></p><ul class="ind">{_rows(orphans, with_type=True)}</ul>'
        )
    if dangling:
        groups.append(
            '<p class="topo-detail-h">Dangling references — a referenced '
            "<code>@id</code> with no matching entity; add the entity or drop the "
            f'reference</p><ul class="ind">{_rows(dangling, with_type=False)}</ul>'
        )

    def _n(count: int, one: str) -> str:
        return f"{count} {one}" + ("" if count == 1 else "s")

    bits = []
    if orphans:
        bits.append(_n(len(orphans), "orphan"))
    if dangling:
        bits.append(_n(len(dangling), "dangling ref"))
    summary = " · ".join(bits) + " — which entities"
    return (
        f'<details class="disc topo-detail"><summary>{summary}</summary>{"".join(groups)}</details>'
    )


def _render_topology_strip(counts: dict[str, int]) -> str:
    """The graph-topology metrics strip (relocated into the Provenance section).

    Renders the crate's entity composition by paper layer (packaging / ISA
    structural / ISA-Tox domain) plus any orphan/dangling-reference flags, from
    the deterministic :func:`build_crate_graph` counts.
    """
    total = counts.get("layer1", 0) + counts.get("layer2", 0) + counts.get("layer3", 0)
    parts = [
        '<span class="topo-label">Graph topology</span>',
        f'<span class="c"><b>{total}</b>&nbsp;entities</span>',
        '<span class="c"><span class="sw" style="background:var(--muted)"></span>'
        f"{counts.get('layer1', 0)} packaging</span>",
        '<span class="c"><span class="sw" style="background:var(--cat-process)"></span>'
        f"{counts.get('layer2', 0)} ISA structural</span>",
        '<span class="c"><span class="sw" style="background:var(--cat-data)"></span>'
        f"{counts.get('layer3', 0)} ISA-Tox domain</span>",
    ]
    flags: list[str] = []
    n_orphan = counts.get("orphan", 0)
    n_dangling = counts.get("dangling", 0)
    if n_orphan:
        flags.append(f"{n_orphan} orphan" + ("" if n_orphan == 1 else "s"))
    if n_dangling:
        flags.append(f"{n_dangling} dangling ref" + ("" if n_dangling == 1 else "s"))
    if flags:
        parts.append(f'<span class="c warnflag">{_mk("no")}&nbsp;{" · ".join(flags)}</span>')
    return f'<div class="comp topo">{"".join(parts)}</div>'


def _legend(*items: str) -> str:
    return f'<div class="prov-legend">{"".join(items)}</div>'


# Legend swatches, drawn with the same outline the diagrams use.
_LG_PROCESS = (
    '<span class="lg"><svg width="20" height="14" aria-hidden="true">'
    '<polygon points="4,1 14,1 18,7 14,13 4,13 1,7" fill="var(--accent-soft)" '
    'stroke="var(--cat-process)" stroke-width="1.6"/></svg> Process</span>'
)
_LG_SAMPLE = (
    '<span class="lg"><svg width="22" height="14" aria-hidden="true">'
    '<rect x="1" y="2" width="20" height="10" rx="5" fill="var(--surface-2)" '
    'stroke="var(--cat-material)" stroke-width="1.6"/></svg> Sample / material</span>'
)
_LG_FILE = (
    '<span class="lg"><svg width="18" height="14" aria-hidden="true">'
    '<rect x="1" y="1" width="15" height="12" rx="2" fill="var(--surface-2)" '
    'stroke="var(--cat-data)" stroke-width="1.6"/></svg> File / table</span>'
)
# Explains the badge `provenance_dag._display_name` puts on a file whose crate
# name carries the AUTOGENERATED marker. Emitted only when such a node is
# actually drawn (see `_render_provenance_panel`) — a legend that explains a
# symbol the reader cannot see teaches them to distrust the legend.
#
# The emoji is `aria-hidden` because it is the thing being defined, not content:
# the sentence beside it carries the meaning, and a screen reader announcing
# "warning" before it would state the conclusion twice.
_LG_AUTOGENERATED = (
    f'<span class="lg"><span class="lg-badge" aria-hidden="true">{AUTOGENERATED_BADGE}</span>'
    " generated by this tool, not supplied with the deposit</span>"
)
_LG_COMPOUND = (
    '<span class="lg"><svg width="22" height="14" aria-hidden="true">'
    '<polygon points="4,1 18,1 21,4 21,10 18,13 4,13 1,10 1,4" fill="var(--surface-2)" '
    'stroke="var(--cat-chemical)" stroke-width="1.6"/></svg> Compound</span>'
)
_LG_CONTAINER = (
    '<span class="lg"><svg width="24" height="14" aria-hidden="true">'
    '<rect x="1" y="2" width="22" height="10" rx="2" fill="var(--surface-2)" '
    'stroke="var(--cat-container)" stroke-width="1.6"/>'
    '<path d="M5,2 V12 M19,2 V12" stroke="var(--cat-container)" stroke-width="1.2"/>'
    '</svg> Investigation / Study / Assay</span>'
)
_LG_CELLLINE = (
    '<span class="lg"><svg width="22" height="14" aria-hidden="true">'
    '<rect x="1" y="2" width="20" height="10" rx="5" fill="var(--surface-2)" '
    'stroke="var(--cat-material)" stroke-width="1.6"/></svg> Cell line / sample</span>'
)
_LG_PERSON = (
    '<span class="lg"><svg width="22" height="14" aria-hidden="true">'
    '<rect x="1" y="2" width="20" height="10" rx="5" fill="var(--surface-2)" '
    'stroke="var(--cat-agent)" stroke-width="1.6"/></svg> Person</span>'
)
_LG_ORG = (
    '<span class="lg"><svg width="22" height="14" aria-hidden="true">'
    '<rect x="1" y="2" width="20" height="10" rx="2" fill="var(--surface-2)" '
    'stroke="var(--cat-org)" stroke-width="1.6"/></svg> Organisation</span>'
)
_LG_LINK = '<span class="lg"><span class="gl"></span> links to</span>'
_LG_BREAK = '<span class="lg"><span class="gl brk"></span> ✗ link missing</span>'


_ISA_LEVEL_NOTE = {
    "Investigation": "the question the crate answers",
    "Study": "a coherent body of work toward it",
    "Assay": "one measurement campaign",
}


def _render_overview_panel(model: dict[str, Any]) -> tuple[str, str]:
    """The All-entities view: the whole crate as one composition map.

    The other views draw edges to answer a question. This one answers "what is in
    here, and how much of it is connected?", for which a node-link diagram is the
    wrong instrument at this scale — the crate's own graph is 188 nodes and
    renders as a hairball. One tile per entity, clustered by category inside its
    paper layer, unreachable ones outlined in alarm colour.

    Returns:
        ``(panel html, tab badge)`` — ``("", "")`` for an empty crate.
    """
    from builder.writers.provenance_dag import render_overview_svg

    nodes = [n for n in (model.get("nodes") or []) if n.get("layer") is not None]
    if not nodes:
        return "", ""
    svg = render_overview_svg(model)
    if not svg:
        return "", ""
    counts = model.get("counts", {})
    orphans = counts.get("orphan", 0)
    reachable = len(nodes) - orphans

    isolated = counts.get("isolated", 0)
    stranded = counts.get("stranded", 0)
    links = counts.get("unreachable_clusters", 0)

    swatches = "".join(
        f'<span class="lg"><span class="ov-key cat-{cat}"></span> {cat}</span>'
        for cat in ("container", "process", "protocol", "material", "chemical",
                    "data", "agent", "publication", "annotation")
    )
    # Only name a state the map actually shows: a key for a tile the reader
    # cannot find is noise, and here it would also misdescribe the crate.
    reach_keys = []
    if isolated:
        reach_keys.append(
            '<span class="lg"><span class="ov-key orphan isolated"></span> '
            "unreachable · linked to nothing</span>"
        )
    if stranded:
        reach_keys.append(
            '<span class="lg"><span class="ov-key orphan stranded"></span> '
            "unreachable · linked to each other, not to the root</span>"
        )
    legend = _legend(swatches, *reach_keys)

    note = (
        f'<p class="chem-warn">{_mk("no")}<span><b>{orphans} of {len(nodes)} entities '
        "are unreachable from the crate root</b> — described in the metadata, but a "
        f"reader walking the crate never arrives at them. {_reach_repair(counts)} "
        "The other views show which links are missing.</span></p>"
        if orphans
        else '<p class="good-note">Every entity is reachable from the crate root.</p>'
    )

    panel = (
        '<p class="prov-cap">Every entity in the crate, one tile each, grouped by '
        "functional category inside its paper layer — the crate's shape and its "
        f"health on one screen. <b>{len(nodes)}</b> entities · <b>{reachable}</b> "
        f"reachable · <b>{orphans}</b> not"
        + (f" · <b>{links}</b> link{'' if links == 1 else 's'} away" if links else "")
        + ".</p>\n"
        f'  <div class="prov-scroll">{svg}</div>\n  {legend}\n'
        f"  {note}"
    )
    return panel, str(len(nodes))


def _reach_repair(counts: dict[str, Any]) -> str:
    """One sentence on how much work the unreachable entities actually are.

    The count of unreachable entities is not the size of the job, and reporting
    it as though it were is discouraging in precisely the wrong direction: an
    island of thirty entities that already reference each other is *one* missing
    link, and the better-connected it is the more alarming the raw number looks.
    This states the number of links instead, and splits the two kinds so a reader
    knows which entities share a fix and which each need their own.
    """
    isolated = int(counts.get("isolated", 0))
    stranded = int(counts.get("stranded", 0))
    links = int(counts.get("unreachable_clusters", 0))
    if not links:
        return ""

    parts = []
    if stranded:
        parts.append(
            f"<b>{stranded}</b> are linked to each other but not to the root"
        )
    if isolated:
        parts.append(f"<b>{isolated}</b> stand entirely alone")
    detail = f" ({'; '.join(parts)})" if parts else ""

    if links == 1:
        return f"They form a single group{detail}, so <b>one link</b> would reconnect them all."
    return (
        f"They form <b>{links}</b> groups{detail}, so <b>{links} links</b> — not "
        f"{counts.get('orphan', 0)} — would reconnect every one of them."
    )


def _render_isa_panel(inv: dict[str, Any]) -> tuple[str, str]:
    """The ISA structure view: the Investigation / Study / Assay backbone.

    ISA is the skeleton the other views hang off, and it is expressed purely as
    ``hasPart`` between Datasets that differ only by ``additionalType`` — so it is
    invisible in the JSON and breaks in ways that still validate: a Study nobody
    lists as a part, an Assay with no process attached, a level with no
    ``identifier`` (which is what makes an ISA node citable at all).

    Returns:
        ``(panel html, tab badge)`` — ``("", "")`` when the crate has no ISA nodes.
    """
    from builder.writers.provenance_dag import ISA_COVERAGE_FIELDS, render_isa_svg

    nodes = inv["nodes"]
    if not nodes:
        return "", ""
    counts = inv["counts"]
    detached = counts["detached"]
    pct = (
        round(counts["fields_met"] / counts["fields_total"] * 100)
        if counts["fields_total"]
        else 0
    )

    svg = render_isa_svg(inv)
    diagram = (
        f'<div class="prov-scroll">{svg}</div>\n  '
        + _legend(_LG_CONTAINER, _LG_LINK, _LG_BREAK)
        if svg
        else ""
    )

    notes = []
    if detached:
        loose = [n["label"] for n in nodes if n["state"] == "detached"]
        notes.append(
            f'<p class="chem-warn">{_mk("no")}<span><b>{detached} ISA container'
            f'{"" if detached == 1 else "s"} sit outside the hierarchy</b> '
            f'({", ".join(loose[:4])}{"&hellip;" if len(loose) > 4 else ""}). '
            "Nothing lists them under <code>hasPart</code>, so a reader walking the "
            "Investigation never reaches them.</span></p>"
        )
    hollow = [n for n in nodes if n["fields"]["Contains the next level"] is False]
    if hollow:
        notes.append(
            f'<p class="chem-warn">{_mk("no")}<span><b>{len(hollow)} container'
            f'{"" if len(hollow) == 1 else "s"} contain nothing below them</b> '
            f'({", ".join(n["label"] for n in hollow[:4])}). An Assay needs a '
            "<code>LabProcess</code>, a Study an Assay, an Investigation a Study — "
            "otherwise the level is a label with no work under it.</span></p>"
        )
    if not notes:
        notes.append(
            '<p class="good-note">The Investigation / Study / Assay hierarchy is complete.</p>'
        )

    head = "".join(
        f'<th scope="col" title="{html.escape(full)}">{html.escape(short)}</th>'
        for full, short in ISA_COVERAGE_FIELDS
    )
    rows = []
    for n in sorted(nodes, key=lambda n: (n["state"] == "linked", n["met"], n["id"])):
        flag = (
            ""
            if n["state"] == "linked"
            else '<span class="chem-flag" title="nothing lists this container under '
            'hasPart">detached</span>'
        )
        extra = (
            f'<span class="ty">{len(n["processes"])} process'
            f'{"" if len(n["processes"]) == 1 else "es"}</span>'
            if n["level"] == "Assay"
            else ""
        )
        cells = "".join(
            f"<td>{_mk(_kind(n['fields'].get(full)))}</td>" for full, _short in ISA_COVERAGE_FIELDS
        )
        rows.append(
            f'<tr><th scope="row">{_mk("ok" if n["state"] == "linked" else "no")}'
            f'<span class="cn">{n["label"]}</span>'
            f'<span class="ty" title="{html.escape(_ISA_LEVEL_NOTE[n["level"]])}">'
            f'{n["level"]}</span>{extra}{flag}</th>{cells}</tr>'
        )
    matrix = (
        '<div class="chem-tbl-scroll"><table class="chem-tbl">'
        '<caption class="sr-only">Structural fields carried by each ISA container</caption>'
        f'<thead><tr><th scope="col">Container</th>{head}</tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table></div>'
    )

    panel = (
        '<p class="prov-cap">The ISA backbone every other view hangs off — the '
        "Investigation that states the question, the Studies under it, and the Assays "
        f"whose processes the Provenance view traces. <b>{counts['investigations']}</b> "
        f"investigation · <b>{counts['studies']}</b> stud"
        f"{'y' if counts['studies'] == 1 else 'ies'} · <b>{counts['assays']}</b> assay"
        f"{'' if counts['assays'] == 1 else 's'} · <b>{counts['processes']}</b> process"
        f"{'' if counts['processes'] == 1 else 'es'} · <b>{pct}%</b> complete.</p>\n"
        f"  {diagram}\n"
        f"  {''.join(notes)}\n"
        f"  {matrix}"
    )
    return panel, str(counts["total"])


def _render_provenance_panel(graph: dict[str, Any] | list[dict[str, Any]]) -> str:
    """The derivation-chain view: materials, processes, and the files produced."""
    from builder.writers.provenance_dag import render_provenance_svg

    svg = render_provenance_svg(graph)
    if not svg:
        return (
            '<p class="lead">No derivation chain recorded — this crate has no LabProcess '
            "input/output edges to trace.</p>"
        )
    items = [
        _LG_PROCESS,
        _LG_SAMPLE,
        _LG_FILE,
        '<span class="lg"><span class="gl obj"></span> consumes (object)</span>',
        '<span class="lg"><span class="gl"></span> produces (result)</span>',
    ]
    # Asked of the rendered SVG rather than the graph: the badge is what needs
    # explaining, so the thing that draws it is the only honest witness to
    # whether it is on the page.
    if AUTOGENERATED_BADGE in svg:
        items.append(_LG_AUTOGENERATED)
    return (
        '<p class="prov-cap">The derivation chain a receiving lab follows to trace an '
        "output back to its inputs — materials, the processes applied, and the files "
        "each step produced.</p>\n"
        f'  <div class="prov-scroll">{svg}</div>\n  ' + _legend(*items)
    )


# The graph views, in tab order: (radio id, panel id, tab label).
_VIEWS: tuple[tuple[str, str, str], ...] = (
    ("mv-all", "p-all", "All entities"),
    ("mv-isa", "p-isa", "ISA structure"),
    ("mv-prov", "p-prov", "Provenance"),
    ("mv-chem", "p-chem", "Chemicals"),
    ("mv-cell", "p-cell", "Cell lines"),
    ("mv-people", "p-people", "People &amp; orgs"),
)


def _render_graph_views_section(
    graph: dict[str, Any] | list[dict[str, Any]], chem_inv: dict[str, Any]
) -> str:
    """The graph-views section: one diagram per tab, over a shared topology strip.

    The three views answer different questions about the same ``@graph`` —
    *how was the result produced* (provenance), *what was tested* (chemicals),
    *who is credited* (people) — and a reader wants one at a time, not three
    stacked diagrams. They are therefore tabbed.

    The tabs are pure CSS (radio inputs + ``:checked ~`` sibling rules), because
    the report is a self-contained offline artifact embedded in the crate and
    carries no script; the radios keep them keyboard-operable, and print styles
    expand every panel so a printed report loses nothing. A view whose diagram
    has no content (a crate with no compounds, or one that credits nobody) drops
    its tab entirely rather than showing an empty panel, and the first surviving
    tab is the one selected.

    Called only when a crate ``@graph`` is supplied.
    """
    from builder.writers.provenance_dag import (
        build_cellline_inventory,
        build_crate_graph,
        build_isa_inventory,
        build_people_inventory,
    )

    model = build_crate_graph(graph, all_edges=True)
    panels = {
        "p-all": _render_overview_panel(model),
        "p-isa": _render_isa_panel(build_isa_inventory(graph)),
        "p-prov": (_render_provenance_panel(graph), ""),
        "p-chem": _render_chemicals_panel(chem_inv),
        "p-cell": _render_celllines_panel(build_cellline_inventory(graph)),
        "p-people": _render_people_panel(build_people_inventory(graph)),
    }
    live = [(rid, pid, label) for rid, pid, label in _VIEWS if panels[pid][0]]

    inputs = "".join(
        f'<input class="tab-in" type="radio" name="mat-view" id="{rid}"'
        f'{" checked" if i == 0 else ""}>'
        for i, (rid, _pid, _label) in enumerate(live)
    )
    tabs = "".join(
        f'<label class="tab" for="{rid}"><span class="tb-n">{label}</span>'
        + (f'<span class="tb-c">{panels[pid][1]}</span>' if panels[pid][1] else "")
        + "</label>"
        for rid, pid, label in live
    )
    bodies = "".join(
        f'<div class="panel" id="{pid}">'
        f'<h3 class="panel-h">{label}</h3>{panels[pid][0]}</div>'
        for _rid, pid, label in live
    )

    return (
        "<section>\n"
        '  <div class="sec-h"><h2>Graph views</h2>'
        f'<span class="sec-meta">{len(live)} view{"" if len(live) == 1 else "s"} '
        "of the same crate</span></div>\n"
        f"  {inputs}\n"
        f'  <div class="tabbar">{tabs}</div>\n'
        f"  {bodies}\n"
        f"  {_render_topology_strip(model.get('counts', {}))}\n"
        f"  {_render_topology_detail(model.get('nodes', []))}\n"
        "</section>\n"
    )


_CHEM_STATE_MARK = {"wired": "ok", "mentioned": "na", "unlinked": "no"}
_CHEM_STATE_NOTE = {
    "wired": "reachable from a process",
    "mentioned": "named in the crate, but produced by no process",
    "unlinked": "nothing in the crate references this compound",
}


def _render_chemicals_panel(inv: dict[str, Any]) -> tuple[str, str]:
    """The Chemicals view: how each compound reaches the experiment, and how
    completely it is identified.

    Two views of the same inventory, because either alone misleads. The diagram
    answers *can a reader get from a process to this compound* — the chain ISA
    forces to run through the condition table rather than the process object, and
    the one that quietly breaks. The matrix answers *could a reader obtain this
    substance* — CAS / PubChem CID / DTXSID plus the structure fields. A crate can
    score perfectly on one and fail the other, so the section never collapses them
    into a single number.

    Returns ``("", "")`` when the crate declares no compounds — the view drops
    its tab entirely, because an empty chemicals panel on a non-chemical crate
    would read as a failure rather than as "not applicable".

    Returns:
        ``(panel html, tab badge)``.
    """
    from builder.writers.provenance_dag import CHEM_COVERAGE_FIELDS, render_chemicals_svg

    chems = inv["chemicals"]
    if not chems:
        return "", ""
    counts = inv["counts"]
    total, wired = counts["total"], counts["wired"]
    id_pct = (
        round(counts["fields_met"] / counts["fields_total"] * 100)
        if counts["fields_total"]
        else 0
    )

    svg = render_chemicals_svg(inv)
    unreached = total - wired
    if unreached:
        route_note = (
            f'<p class="chem-warn">{_mk("no")}<span><b>{unreached} of {total} compounds '
            "cannot be reached from any process.</b> ISA forbids a MolecularEntity as a "
            "LabProcess <code>object</code>, so a compound is linked <em>through</em> the "
            "Exposure&rsquo;s condition table — give the table an <code>about</code> "
            "pointing at the compound (and the <code>compound</code> column a "
            "<code>valueUrl</code>), or the substance stays described but unused.</span></p>"
        )
    else:
        route_note = (
            '<p class="good-note">Every compound is reachable from the process that used it.</p>'
        )

    # Per-compound identification matrix. Unwired first, then worst-covered, so
    # the rows that survive the cap are the ones worth acting on.
    ordered = sorted(
        chems, key=lambda c: (c["state"] == "wired", c["met"], c["name"].casefold(), c["id"])
    )
    head = "".join(
        f'<th scope="col" title="{html.escape(full)}">{html.escape(short)}</th>'
        for full, short in CHEM_COVERAGE_FIELDS
    )
    # Every compound is listed, matching the diagram: this is a metadata-checking
    # view, and a truncated tail hides the rows worth acting on.
    rows = []
    for c in ordered:
        link = " 🔗" if c["resolvable"] else ""
        flag = (
            ""
            if c["state"] == "wired"
            else f'<span class="chem-flag" title="{html.escape(_CHEM_STATE_NOTE[c["state"]])}">'
            f"{'not linked' if c['state'] == 'unlinked' else 'no process'}</span>"
        )
        cells = "".join(
            f'<td>{_mk("ok" if c["fields"].get(full) else "no")}</td>'
            for full, _short in CHEM_COVERAGE_FIELDS
        )
        rows.append(
            f'<tr><th scope="row">{_mk(_CHEM_STATE_MARK[c["state"]])}'
            f'<span class="cn">{c["label"]}{link}</span>{flag}</th>{cells}</tr>'
        )
    matrix = (
        '<div class="chem-tbl-scroll"><table class="chem-tbl">'
        f'<caption class="sr-only">Identification fields carried by each compound</caption>'
        f'<thead><tr><th scope="col">Compound</th>{head}</tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table></div>'
    )

    diagram = (
        f'<div class="prov-scroll">{svg}</div>\n  '
        + _legend(_LG_PROCESS, _LG_FILE, _LG_COMPOUND, _LG_LINK, _LG_BREAK)
        if svg
        else ""
    )

    panel = (
        '<p class="prov-cap">The substances under test — whether each one is actually '
        "connected to the experiment that used it, and whether a reader could obtain the "
        f"same material. <b>{total}</b> compound{'' if total == 1 else 's'} · "
        f"<b>{wired}</b> wired · <b>{id_pct}%</b> identified.</p>\n"
        f"  {diagram}\n"
        f"  {route_note}\n"
        f"  {matrix}"
    )
    return panel, str(total)


# An organisation reached through a person's affiliation is CORRECTLY linked —
# that is the normal shape — so it reads as met, with a muted chip naming the
# route. Only "unattached" is a defect.
_CELL_STATE_NOTE = {
    "wired": "consumed by a process",
    "mentioned": "named in the crate, but consumed by no process",
    "unlinked": "nothing in the crate references this cell line",
}


def _render_celllines_panel(inv: dict[str, Any]) -> tuple[str, str]:
    """The Cell lines view: the biological test system, and whether it is pinned down.

    The same two questions the compound view asks, because a cell line fails the
    same two ways. It is *unreachable* when the ``CellCulture`` consumes a freshly
    minted generic ``Sample`` instead of the declared ``CellLineSample`` — the
    line is then described and used by nothing. It is *unidentified* when it
    carries a name but no Cellosaurus RRID: "CHO-K1" names a family of divergent
    stocks, ``CVCL_0214`` names one, and organ / tissue / passage are what let
    another lab reproduce the culture rather than merely recognise it.

    Returns:
        ``(panel html, tab badge)`` — ``("", "")`` when the crate declares none.
    """
    from builder.writers.provenance_dag import CELLLINE_COVERAGE_FIELDS, render_celllines_svg

    lines = inv["celllines"]
    if not lines:
        return "", ""
    counts = inv["counts"]
    total, wired = counts["total"], counts["wired"]
    rrid_backed = sum(1 for c in lines if c["rrid"])
    pct = (
        round(counts["fields_met"] / counts["fields_total"] * 100)
        if counts["fields_total"]
        else 0
    )

    svg = render_celllines_svg(inv)
    diagram = (
        f'<div class="prov-scroll">{svg}</div>\n  '
        + _legend(_LG_PROCESS, _LG_CELLLINE, _LG_FILE, _LG_LINK, _LG_BREAK)
        if svg
        else ""
    )

    notes = []
    unreached = total - wired
    if unreached:
        notes.append(
            f'<p class="chem-warn">{_mk("no")}<span><b>{unreached} of {total} cell lines are '
            "not consumed by any process.</b> The <code>CellCulture</code> should take the "
            "declared cell line as its <code>input</code> — when it takes a freshly minted "
            "generic <code>Sample</code> instead, the line is described in the crate and used "
            "by nothing.</span></p>"
        )
    if total - rrid_backed:
        notes.append(
            f'<p class="chem-warn">{_mk("no")}<span><b>{total - rrid_backed} of {total} cell '
            "lines carry no Cellosaurus RRID.</b> A name identifies a family of divergent "
            "stocks; <code>CVCL_…</code> identifies the one that was used.</span></p>"
        )
    if not notes:
        notes.append(
            '<p class="good-note">Every cell line is consumed by a process and RRID-backed.</p>'
        )

    ordered = sorted(
        lines, key=lambda c: (c["state"] == "wired", c["met"], c["name"].casefold(), c["id"])
    )
    head = "".join(
        f'<th scope="col" title="{html.escape(full)}">{html.escape(short)}</th>'
        for full, short in CELLLINE_COVERAGE_FIELDS
    )
    rows = []
    for c in ordered:
        link = " 🔗" if c["resolvable"] else ""
        rrid = f'<span class="ty">{html.escape(c["rrid"])}</span>' if c["rrid"] else ""
        flag = (
            ""
            if c["state"] == "wired"
            else f'<span class="chem-flag" title="{html.escape(_CELL_STATE_NOTE[c["state"]])}">'
            f"{'not linked' if c['state'] == 'unlinked' else 'no process'}</span>"
        )
        cells = "".join(
            f'<td>{_mk("ok" if c["fields"].get(full) else "no")}</td>'
            for full, _short in CELLLINE_COVERAGE_FIELDS
        )
        rows.append(
            f'<tr><th scope="row">{_mk(_CHEM_STATE_MARK[c["state"]])}'
            f'<span class="cn">{c["label"]}{link}</span>{rrid}{flag}</th>{cells}</tr>'
        )
    matrix = (
        '<div class="chem-tbl-scroll"><table class="chem-tbl">'
        '<caption class="sr-only">Identification fields carried by each cell line</caption>'
        f'<thead><tr><th scope="col">Cell line</th>{head}</tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table></div>'
    )

    panel = (
        '<p class="prov-cap">The biological test system — whether the declared line is the '
        "one the culture actually consumed, and whether another lab could obtain the same "
        f"stock. <b>{total}</b> cell line{'' if total == 1 else 's'} · <b>{wired}</b> "
        f"consumed by a process · <b>{pct}%</b> characterised.</p>\n"
        f"  {diagram}\n"
        f"  {''.join(notes)}\n"
        f"  {matrix}"
    )
    return panel, str(total)


_AGENT_STATE_MARK = {"credited": "ok", "affiliated": "ok", "unattached": "no"}
_AGENT_STATE_NOTE = {
    "credited": "credited directly by an entity in the crate",
    "affiliated": "linked through a person's affiliation",
    "unattached": "nothing in the crate references this agent",
}
_AGENT_STATE_CHIP = {"affiliated": ("muted", "via affiliation"), "unattached": ("", "unattached")}
def _render_people_panel(inv: dict[str, Any]) -> tuple[str, str]:
    """The People & organisations view: who the crate credits, how resolvably.

    Attribution is where a crate quietly stops being machine-actionable. A bare
    ``name`` satisfies every profile while crediting nobody a registry can
    resolve, and the diagram makes the two failure shapes visible: a person with
    no ``affiliation`` (the institution behind the work is unrecorded) and an
    agent nothing references at all — which is what a duplicated institution
    looks like, one copy ROR-backed and carrying edges, the other locally minted
    and carrying none.

    Returns ``("", "")`` when the crate names no people or organisations.

    Returns:
        ``(panel html, tab badge)``.
    """
    from builder.writers.provenance_dag import AGENT_COVERAGE_FIELDS, render_people_svg

    agents = inv["agents"]
    if not agents:
        return "", ""
    counts = inv["counts"]
    total, pid_backed, unattached = counts["total"], counts["pid_backed"], counts["unattached"]

    svg = render_people_svg(inv)
    diagram = (
        f'<div class="prov-scroll">{svg}</div>\n  '
        + _legend(_LG_PERSON, _LG_ORG, _LG_LINK, _LG_BREAK)
        if svg
        else ""
    )

    notes = []
    if unattached:
        loose = [a["label"] for a in agents if a["state"] == "unattached"]
        notes.append(
            f'<p class="chem-warn">{_mk("no")}<span><b>{unattached} of {total} agents are '
            "referenced by nothing in the crate</b> "
            f"({', '.join(loose[:4])}{'…' if len(loose) > 4 else ''}). An agent no entity "
            "credits is usually a duplicate of one that is — the same institution minted "
            "twice, once with its ROR and once locally. Point the crediting entity at the "
            "identifier-backed copy and drop the other.</span></p>"
        )
    missing_pid = total - pid_backed
    if missing_pid:
        notes.append(
            f'<p class="chem-warn">{_mk("no")}<span><b>{missing_pid} of {total} agents carry '
            "no persistent identifier.</b> Give each person an ORCID and each organisation a "
            "ROR — a name string credits nobody a machine can resolve.</span></p>"
        )
    if not notes:
        notes.append(
            '<p class="good-note">Every agent is credited and identifier-backed.</p>'
        )

    ordered = sorted(
        agents, key=lambda a: (a["state"] == "credited", a["met"], a["name"].casefold(), a["id"])
    )
    head = "".join(
        f'<th scope="col" title="{html.escape(full)}">{html.escape(short)}</th>'
        for full, short in AGENT_COVERAGE_FIELDS
    )
    # Every agent is listed — no cap. This view exists so a person can CHECK the
    # attribution entity by entity, and a truncated tail is exactly where a
    # duplicated institution or a missing-ORCID author would hide.
    rows = []
    for a in ordered:
        link = " 🔗" if a["resolvable"] else ""
        chip = _AGENT_STATE_CHIP.get(a["state"])
        flag = (
            ""
            if chip is None
            else f'<span class="chem-flag{" " + chip[0] if chip[0] else ""}" '
            f'title="{html.escape(_AGENT_STATE_NOTE[a["state"]])}">{chip[1]}</span>'
        )
        kind = "Person" if a["kind"] == "person" else "Organisation"
        cells = "".join(
            f"<td>{_mk(_kind(a['fields'].get(full)))}</td>"
            for full, _short in AGENT_COVERAGE_FIELDS
        )
        rows.append(
            f'<tr><th scope="row">{_mk(_AGENT_STATE_MARK[a["state"]])}'
            f'<span class="cn">{a["label"]}{link}</span>'
            f'<span class="ty">{kind}</span>{flag}</th>{cells}</tr>'
        )
    matrix = (
        '<div class="chem-tbl-scroll"><table class="chem-tbl">'
        '<caption class="sr-only">Attribution fields carried by each agent</caption>'
        f'<thead><tr><th scope="col">Agent</th>{head}</tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table></div>'
    )

    panel = (
        '<p class="prov-cap">Who the crate credits, and whether that credit resolves — '
        f"an ORCID for a person, a ROR for an institution. <b>{counts['people']}</b> "
        f"{'person' if counts['people'] == 1 else 'people'} · <b>{counts['orgs']}</b> "
        f"organisation{'' if counts['orgs'] == 1 else 's'} · <b>{pid_backed}</b> "
        "identifier-backed.</p>\n"
        f"  {diagram}\n"
        f"  {''.join(notes)}\n"
        f"  {matrix}"
    )
    return panel, str(total)


def build_maturity_html(
    state: CrateState,
    *,
    validation: ValidationReport | None = None,
    graph: dict[str, Any] | list[dict[str, Any]] | None = None,
) -> str:
    """Render the maturity report HTML for *state*.

    The profile-adherence section is rendered from the crate's existing
    validation results (``validation`` or, by default, ``state.validation``) —
    NOT by re-running the SHACL validator. That keeps report generation cheap so
    embedding it in ``export_crate`` adds no validation cost (#85); validation is
    a separate step (e.g. ``build_and_validate`` in the agent loop). If no
    validation has run, the section says so. Adherence is reported across the
    three severity tiers Required / Recommended / Optional (#306); an unevaluated
    SHOULD/MAY tier renders as "not assessed", never a false green zero.

    When a crate ``graph`` (the ``@graph`` from ``crate.metadata.generate()``) is
    supplied, the report also folds in a Provenance & graph section: the LabProcess
    derivation chain drawn as a self-contained inline SVG, plus a graph-topology
    strip (entity composition by paper layer, orphan/dangling flags). Omitting
    ``graph`` skips that section — the report is still complete without it.

    Args:
        state: The crate state being reported on.
        validation: Validation results to render. Defaults to
            ``state.validation``.
        graph: The crate's serialized ``@graph`` (or the full metadata document)
            used to render the provenance chain and topology strip. When ``None``
            the Provenance & graph section is omitted — but MIT coverage is
            still scored against an assembled graph, which the assessor then
            builds itself (#311). Omitting ``graph`` costs one extra in-memory
            assembly and reports on that document: it is a real measurement of a
            real crate, at worst marginally more conservative than the export
            document (``_assemble_graph`` leaves out auto-included scanned-file
            leaves). What it is never again is 0% for a crate nobody scored.
    """
    esc = html.escape
    title = state.metadata.title or "RO-Crate"
    accession = state.metadata.accession or ""
    # MIT is scored against the assembled @graph — the crate_slot vocabulary
    # describes the serialized crate, not CrateState (#311). The export path
    # passes the graph it already built; without one the assessor assembles its
    # own rather than report a number it did not measure. Either way the report
    # prints a real measurement or "not assessed", never a 0% nobody computed.
    mit = assess_mit_coverage(state, graph=graph)
    # Feed that MIT result into FAIR so the mit_coverage indicator (RDA-R1.3-01D)
    # reflects the graph-based coverage — state.mit_assessment is never populated
    # on this path (#311).
    fair = assess_fair_maturity(state, mit=mit)
    val = validation if validation is not None else state.validation

    tiers = _severity_tiers(val) if _validation_has_signal(val) else None
    # Does the recorded verdict still describe THIS state? `export_crate`
    # re-validates when it does not, so a stale banner here means the report was
    # built directly from a state that outran its last validation.
    stale = tiers is not None and val.is_stale_for(state)
    if stale:
        for tier in tiers:
            tier["state"] = "na"
            # The summary goes too: "3 / 3 profiles" asserts a pass just as
            # loudly as a green tick, and it was measured on a different crate.
            tier["summary"] = "out of date"
            tier["note"] = "Recorded before the crate's latest changes."
    checks = _reproducibility_checks(state)
    repro_ready = sum(1 for _, ok, _ in checks if ok)

    header = _render_header(title, accession, tiers, stale=stale)
    # The chemicals inventory is shared: it feeds the KPI tile and the Chemicals
    # graph view, and is a single cheap pass over the graph — build it once.
    chem_inv: dict[str, Any] | None = None
    views_section = ""
    if graph is not None:
        from builder.writers.provenance_dag import build_chemical_inventory

        chem_inv = build_chemical_inventory(graph)
        views_section = _render_graph_views_section(graph, chem_inv)
    kpis = _render_kpis(
        tiers,
        fair,
        mit,
        repro_ready,
        len(checks),
        chem_inv if chem_inv and chem_inv["chemicals"] else None,
    )
    prof_section = _render_profile_section(val, tiers, stale=stale)
    fair_section = _render_fair_section(fair)
    mit_section = _render_mit_section(mit)
    repro_section = _render_repro_section(checks)

    footer = (
        "<footer><span>Generated by vitro-crate · ro-crate-metadata-maturity.html</span>"
        "<span>Self-contained · offline · print-friendly</span></footer>\n"
    )
    body = (
        header
        + kpis
        + views_section
        + prof_section
        + fair_section
        + mit_section
        + repro_section
        + footer
    )

    # Fill the shell placeholders. STYLE and BODY first (neither can contain a
    # sentinel), TITLE last so crate-controlled text can never re-trigger a
    # replacement.
    return (
        _load_shell()
        .replace("__STYLE__", _load_css())
        .replace("__BODY__", body)
        .replace("__TITLE__", esc(title))
    )
